### ISSUE TITLE
bootstrap.sh: dynamic UPSTREAM_URL for offline install

### ISSUE THREAD

**Issue by hackacad** [BastilleBSD/bastille#100]
FEATURE REQUEST

I would be nice to change UPSTREAM_URL (bootstrap.sh) as config parameter in bastille.conf.
This would give Bastille the functionality for offline installation.

**Comment by hackacad** [comment]
#100 yay!

**Comment by JRGTH** [comment]
I think `UPSTREAM_URL` should be placed in `bastille.conf` for the currently supported distros, including an user optional one.

+-> TODO list

Regards

**Comment by hackacad** [comment]
check #112

**Comment by cedwards** [comment]
Way to close your own issue with a patch.
