### ISSUE TITLE
Error about pkg not available when applying template.

### ISSUE THREAD

**Issue by bmac2** [BastilleBSD/bastille#11]
root@jailbeast:/usr/local/bastille/templates # bastille template md-mail postfix
[md-mail]:
Copying files...
Copy complete.
Installing packages.
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly, please wait...
pkg: Error fetching http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly, please wait...
pkg: Error fetching http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly, please wait...
pkg: Error fetching http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Updating services.
sendmail_enable: NONE -> NO
sendmail_submit_enable: YES -> NO
sendmail_outbound_enable: YES -> NO
sendmail_msp_queue_enable: YES -> NO
postfix_enable:  -> YES
dovecot_enable:  -> YES
Executing final command(s).
chsh: WARNING: shell '/usr/local/bin/zsh' does not exist
pwd_mkdb: warning, unknown root shell
chsh: user information updated
Template Complete.

[rmd-mail]:
Copying files...
Copy complete.
Installing packages.
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly, please wait...

**Comment by cedwards** [comment]
Closing.
Networking issue.
