### ISSUE TITLE
[Question] layering templates

### ISSUE THREAD

**Issue by ngortheone** [BastilleBSD/bastille#111]
First of all I want to say thanks for the great work you are doing. Proper container orchestration is something that should have been done long time ago.

I have a question regarding template re-use. For example I want to base my template on top of another template. Think of "FROM" directive in `Dockerfile`. Is this possible at the moment?

**Comment by cedwards** [comment]
I recommend looking at the `INCLUDE` template hook. This allows you to include other template(s) in a template. Note: INCLUDE hooks are executed early meaning they will be applied first and the template including them automatically after.

See the example here in one of my personal templates that includes my "base" template before applying my zsh shell template: https://github.com/cedwards/zsh-antigen

`INCLUDE` hooks support URL or template path (relative to template base directory).
