### ISSUE TITLE
[enhancement] bastille destroy -f / stop and destroy

### ISSUE THREAD

**Issue by hackacad** [BastilleBSD/bastille#116]
feature request:
adding force option to destroy.sh

**Comment by cedwards** [comment]
What's the use-case where standard destroy isn't enough?

**Comment by hackacad** [comment]
This might be useful if jail is running. 
-f = force destroy 

Simply check if jail is running an shut it down (shouldn’t be standard option)

**Comment by JRGTH** [comment]
Hello, this option has been added in this [maintenance commit](https://github.com/BastilleBSD/bastille/pull/121/commits/9681254d765e942d6dd2103dcfa581c3dee90ea1#diff-2f26611afbefb67152b01350f7879f45)

The available option are `-f|--forcestop` perhaps it can also be named like `-f|--forcedestroy` or alike but the `-f` switch will just suffice.

As suggested this will attempt to force stop the container before destroy, also the `-f` options has no effect when destroying releases.

Regards
