### ISSUE TITLE
running template more than once

### ISSUE THREAD

**Issue by bmac2** [BastilleBSD/bastille#12]
if I run the template to a jail more than once instead of the rc.conf getting left alone if something is laready set, it make the value =  NONO  or YESYES  instead of correctly working from the entries inside SYSRC file

**Comment by cedwards** [comment]
Thank you for pointing this out. The solution I just merged can be re-run all day and I haven't been able to break it.

The only thing is you've got to follow the hook standard for `SYSRC`:
- one `sysrc` command per-line.
- do NOT use quotes (`"`,`'`) in your sysrc commands *OR*
- if using quotes, make sure you escape them (`\"`)
