### ISSUE TITLE
[ENHANCEMENT] create separate ZFS tanks for jail

### ISSUE THREAD

**Issue by hackacad** [BastilleBSD/bastille#129]
I think it could be useful to put every jail into separate ZFS tanks.

That should make it much easier to migrate jails (e.g. moving it to a new host) and give the ability to zfs snapshot single jails (if you don't want a full export).

**Comment by cedwards** [comment]
If ZFS is enabled this is already the case. ZFS snapshotting is available and `bastille export` uses a ZFS snapshot.

**Comment by hackacad** [comment]
This one isn't working for me as well.
Maybe it's again a general issue when using 'make install'?

root@srslt01:~ # ls /usr/local/bastille/jails/
grep1   grep2   grep3   grep4   grep5   grep6   iptest  iptest3 iptest4 iptest5 iptest6 iptest8 tmp

root@srslt01:~ # zfs list
NAME                                   USED  AVAIL  REFER  MOUNTPOINT
zroot                                 14.5G  2.91G    96K  /zroot
zroot/ROOT                            12.8G  2.91G    96K  none
zroot/ROOT/default                    12.8G  2.91G  12.8G  /
zroot/bastille                         643M  2.91G  86.8M  /usr/local/bastille
zroot/bastille/cache                   154M  2.91G    88K  /usr/local/bastille/cache
zroot/bastille/cache/12.1-RELEASE      154M  2.91G   154M  /usr/local/bastille/cache/12.1-RELEASE
zroot/bastille/logs                    136K  2.91G   136K  /usr/local/bastille/logs
zroot/bastille/releases                402M  2.91G    88K  /usr/local/bastille/releases
zroot/bastille/releases/12.1-RELEASE   402M  2.91G   402M  /usr/local/bastille/releases/12.1-RELEASE
zroot/bastille/templates                88K  2.91G    88K  /usr/local/bastille/templates

**Comment by hackacad** [comment]
It seems like an general issue when using `make install` on an existing system.
