### ISSUE TITLE
[ENHANCEMENT] bastille list does not show stopped/inactive jail

### ISSUE THREAD

**Issue by hackacad** [BastilleBSD/bastille#131]
Solution could be iterating through jails/*/jail.conf and grepping the information.
Might be diffed to `jls (-a)`, showing if jail is active or inactive.

**Comment by cedwards** [comment]
The `bastille list` command takes a number of options including: `(jail(s)|container(s))`, `log(s)`, `template(s)`, `(backup(s)|export(s))` and `release(s)`. The first mentioned option will show stopped and inactive containers.

`bastille list jails`
`bastille list templates`
`bastille list releases`
...

**Comment by hackacad** [comment]
That doesn't work for me.
Maybe ZFS issue?

root@bastille:~ # bastille list
 JID             IP Address      Hostname                      Path
 iptest5         10.0.10.2       iptest5                       /usr/local/bastille/jails/iptest5/root
 grep2           110.0.10.10     grep2                         /usr/local/bastille/jails/grep2/root
 grep3           10.0.10.10      grep3                         /usr/local/bastille/jails/grep3/root
 grep6           10.0.10.1       grep6                         /usr/local/bastille/jails/grep6/root
root@bastille:~ # ls /usr/local/bastille/jails/
grep1   grep2   grep3   grep4   grep5   grep6   iptest  iptest3 iptest4 iptest5 iptest6 iptest8 tmp

All created in a row, but without starting earch.

**Comment by hackacad** [comment]
> bastille list

 without additional (like jails) arguments only shows running jails
