### ISSUE TITLE
[Question] How to switch to ZFS?

### ISSUE THREAD

**Issue by jdek** [BastilleBSD/bastille#136]
Unfortunately I did not see the notice on how to setup ZFS (since it wasn't visible in the documentation) but after I found the README in GitHub I realised I hadn't set it up properly.

I assume it would be a manual process, but how would you go about switching to ZFS after-the-fact?

**Comment by cedwards** [comment]
I don't have much to offer in terms of a UFS to ZFS migration path without manual work... if you can backup the `/usr/local/bastille` contents it could be replaced on top of ZFS after the steps below.

The simplest solution would be to start fresh by stopping and destroying all jails and releases and recursively deleting the `/usr/local/bastille` directory.

At this point update `bastille_zfs_enable="YES"` and `bastille_zfs_zpool="XXX"` (XXX being your zpool) in the configuration.

Finally, re-bootstrap and Bastille will rebuild everything using ZFS.

**Comment by jdek** [comment]
Yep, thanks this is pretty much what I figured would be best. Worked mostly (with a couple things which didn't copy properly but I fixed it). Thanks!
