### ISSUE TITLE
Start hangs for some jails

### ISSUE THREAD

**Issue by jdek** [BastilleBSD/bastille#149]
I have a jail which is extremely slow to start with bastille (only has Nginx in it). I have other jails which work fine (and run instantly) within bastille.

I was debugging using `sh -x` and it hangs on this line:
https://github.com/BastilleBSD/bastille/blob/master/usr/local/share/bastille/start.sh#L76

If I run `jail -f /usr/local/bastille/jails/www/jail.conf -c www` manually outside bastille it runs instantly.

**Comment by cedwards** [comment]
A couple of us have been trying to replicate this without success.

In an attempt to gather more data could you try the small patch of properly quoting `${_jail}` on L76? ie; `"${_jail}"`.

My next troubleshooting suggestion may be to destroy/re-create the container. Admittedly that isn't a good "fix", but I'm curious about behavior and if we can reproduce the issue consistently.

**Comment by jdek** [comment]
Quoting the jail variable here does nothing. Inside the jail, nginx (the only service enabled) starts/restarts instantly, so I'm really stumped. Whats the best way to rebuild the jail with the same name? Copy out configs, delete, create, reinstall, copy in configs?

**Comment by cedwards** [comment]
Those steps should work manually, yes.

Can you also verify for me your platform, version and install method? (ie; FreeBSD, 12.1, pkg install bastille)

**Comment by jdek** [comment]
FreeBSD, 12.1, pkg install bastille is correct yes

**Comment by jdek** [comment]
Seems to fix it, no idea what the issue was. I think I will be switching away from using jails anyway (will be using different VMs on an internal network).
