### ISSUE TITLE
Feature Request: Option for Start/Stop on Boot

### ISSUE THREAD

**Issue by zenny** [BastilleBSD/bastille#155]
Hi,

`jail_enable="NO"` disables jails booting universally.

Is there a parameter in bastillebsd that enables certain jails to disable starting on host boot?

Did I miss something?

Thanks!
/z

**Comment by cedwards** [comment]
`bastille_enable=YES` will start ALL at boot.
`bastille_list="foo bar baz" will selectively start only foo, bar and baz.

**Comment by zenny** [comment]
> `sysrc bastille_enable=YES` will start ALL at boot.
> `sysrc bastille_list="foo bar baz"` will selectively start only foo, bar and baz.

@cedwards Thanks for useful pointer, worth including in README.

**Comment by cedwards** [comment]
Good feedback.

It does appear the only place that is documented is in the [Bastille Getting Started Guide](https://bastillebsd.org/getting-started/).

I'll create an item to update the rest of the documentation accordingly.

**Comment by zenny** [comment]
> Good feedback.
> 
> It does appear the only place that is documented is in the [Bastille Getting Started Guide](https://bastillebsd.org/getting-started/).
> 
> I'll create an item to update the rest of the documentation accordingly.

Thanks for the pointer, but it would be nice to have in the man pages as well as in the README file, imho. Scattered documentation confuses people.

Cheers,
/z

**Comment by hackacad** [comment]
This issue (lack of documentation) was fixed in  #187 as mentioned above.
@zenny could this issue be closed?

**Comment by cedwards** [comment]
Closing now that this has been addressed in more documentation.
