### ISSUE TITLE
[Question] move network interface to jail

### ISSUE THREAD

**Issue by ngortheone** [BastilleBSD/bastille#163]
Hi @cedwards 

First off, thanks for awesome work!

I am considering Bastille for building a production jail host.
 I need to delegate a physical network interface to a jail, exactly like in `man ifconfig` :

```
   vnet jail
             Move the interface to the jail(8), specified by name or JID.  If
             the jail has a virtual network stack, the interface will
             disappear from the current environment and become visible to the
             jail.
```

**Use case**: for security I need to separate management interface (the one that has SSH listening) from public interface (that serves live traffic). Management interface should only be accessible to the jail host, while public interface should be accessible from a jail. At this moment I don't need any integration with pf/ipfw as firewall rules are going to be enforced by AWS security groups.

Is it currently possible to achieve with Bastille?

Thanks.

**Comment by cedwards** [comment]
This functionality was added just this past week. It will be included in 0.6.20200224.

`bastille create -V name release ip/subnet interface`
ie; `bastille create -V folsom 12.1-RELEASE 10.17.89.13/24 lagg0`

Note: the interface is required for VNET and is the name of the external interface to additionally attach to the same bridge as the virtual networked container. This will allow inbound/outbound as you request.
