### ISSUE TITLE
[doc] explain to install jib 

### ISSUE THREAD

**Issue by Johanhen** [BastilleBSD/bastille#167]
In the installation notes and on the documentation page there is no mention to copy the jib or jng files from /usr/share/examples/jails/{jib,jng} files to /usr/sbin/{jib,jng}.

This needs to be done before people can use VNET enabled jails.

**Comment by cedwards** [comment]
`jib` should be copied automatically during create of VNET. If not, this is a bug.

**Comment by Johanhen** [comment]
I see, i assumed , where i should have not that it would not do that.
Nice, you can close this issue .
