### ISSUE TITLE
Some details `bastille create` may need to take care of

### ISSUE THREAD

**Issue by lifepillar** [BastilleBSD/bastille#171]
I am testing Bastille v0.6.20200202 and I like it a lot so far. On comparing my notes for creating jails with what `bastille create` does, I have noticed the following:

1. Bastille does not set strict permissions on a jail's directory, e.g.:

```
chmod 700 ${bastille_prefix}/jails/${myjail}
```

2. Bastille does not disable the `adjkerntz` job from `crontab`, as suggested in the [FreeBSD Handbook](https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/jails-ezjail.html).

3. Bastille does not create a dummy `fstab` in the jail:

```
touch ${myjail}/root/etc/fstab
```

but some programs may expect that file to exist (e.g., see *FreeBSD Mastery: Jails*, Ch. 2).

Just pointing these to your attention.

**Comment by Johanhen** [comment]
There seems to be some performance issues when using vnet. Setting the following should help with that.
hw.vtnet.lro_disable=1 >> /boot/loader.conf  
Maybe mention it in the README or install docs !

**Comment by JRGTH** [comment]
Hi, most of this post-create misc configurations has been covered on this [PR](https://github.com/BastilleBSD/bastille/pull/229/commits/3872f930639fa6c2b8be9f3471f2ea463063bcbf).

Regards

**Comment by chriswells0** [comment]
Everything in this request except for `hw.vtnet.lro_disable=1` has been covered already. Do you want me to add that to the default template for vnet jails? I don't know anything about vnet jails, so I don't know if it should be a default setting.

**Comment by cedwards** [comment]
`vtnet` is VirtIO Ethernet driver. This would apply to virtual FreeBSD systems (cloud) and not physical.
