### ISSUE TITLE
INCLUDE calls "bastille bootstrap"

### ISSUE THREAD

**Issue by zilti** [BastilleBSD/bastille#172]
Bastille calls "bastille bootstrap" for templates listed in an INCLUDE file. Pretty sure it should be "bastille template" instead?

**Comment by cedwards** [comment]
Current behavior should attempt to bootstrap + apply if it finds a URL in the INCLUDE. If it finds a relative path (eg; `bastillebsd-templates/nginx`) it should apply without bootstrapping.

If this isn't the case it's a bug and I can look into it.

**Comment by zilti** [comment]
Well it definitely attempts to bootstrap, but that fails because it calls the command incorrectly. Subsequently it also doesn't apply the template.
