### ISSUE TITLE
[ENHANCEMENT] IPv6 / IPv4 : dual stack.

### ISSUE THREAD

**Issue by xbeaudouin** [BastilleBSD/bastille#179]
**Is your feature request related to a problem? Please describe.**

Well seems we can provide either ipv4 OR ipv6 for a jail, but I really both. How ?

**Describe the solution you'd like**

something like bastille create jail 192.0.2.1 (interface) -inet6 fd00:dead:beef::/64 ?

**Comment by evilham** [comment]
Testing out bastille I ran across this issue.

There is actually a bug, in that providing an IPv6 for the IP parameter results in that being put in `/etc/rc.conf` as:

    ifconfig_vnet0="inet fd00::beef/64"

Which does not work.

**Comment by jpds** [comment]
A VNET jail needs to be used for proper IPv6 connectivity (as I've described [here](https://github.com/BastilleBSD/bastille/issues/241#issuecomment-1483835851).

Once you have that in place, dual-stack works as it does on any FreeBSD host in `/etc/rc.conf` after you've created the jail.

**Comment by adriel-tech** [comment]
I usually make a VNET jail and I have a template 'snippet_ipv6' that I run which enables ipv6. I use SLAAC and don't have static IP's.

~~~
SYSRC ipv6_privacy="YES"
SYSRC ipv6_activate_all_interfaces="YES"
SYSRC rtsold_enable="YES"
SYSRC rtsold_flags="-aFm"
~~~

I realize this is a little bit different from what you are looking to do, just thought I'd throw it out there.

**Comment by bmac2** [comment]
October 2023 release supports dual stack addresses.  There will be further testing and a work around is given above.   Closing as complete.
