### ISSUE TITLE
[ENHANCEMENT] bastille import /path/to/file

### ISSUE THREAD

**Issue by hackacad** [BastilleBSD/bastille#180]
**Is your feature request related to a problem? Please describe.**
`bastille import` (by design) looks for files in bastille_backups_dir (default /usr/local/bastille/backups)
If you import a file with full path (e.g. bastille import /bastilledir/backups/folsom_2020-03-26.txz) you'll get an `awk` error.

**Describe the solution you'd like**
There's three possible options:
(1) add feature to use full path

OR:  
**Describe alternatives you've considered**
(2) trim every path (force using backups_dir)
(3) STDERR that file does not exists OR you shouldn't use full path (maybe adding `echo place in $bastille_backups_dir and use 'bastille import filename.gz'

**Additional context**
@cedwards any prefered solution? (3) would have smallest footprint (just grep for "/" before import); (1) would be the Gucci solution
Let me know which one should be implemented.

**Comment by JRGTH** [comment]
Hi hackacad, I will have a look in to this.

Regards

**Comment by JRGTH** [comment]
Enhancement added in [7db47f3 ](https://github.com/BastilleBSD/bastille/pull/184/commits/7db47f3dac21e0b96be2d3e6117ec784b01bba3b)

Regards

**Comment by cedwards** [comment]
If the merged enhancement is adequate we'll close this?

**Comment by hackacad** [comment]
Close with #184
