### ISSUE TITLE
[ENHANCEMENT] Convert to vnet

### ISSUE THREAD

**Issue by OnigamiSama** [BastilleBSD/bastille#185]
**Is your feature request related to a problem? Please describe.**
So I wanted to try vnet jails because some services might not be running in "regular" jails, like qbittorrent

**Describe the solution you'd like**
Would be great to be able to convert a regular jail to a vnet one like we can do with thin to thick jails

**Describe alternatives you've considered**
I'm currently exporting my jail, gonna tweak the jail.conf by hand to try to make vnet work

**Additional context**
Nothing more to says other that all my next jails will be thick and vnet ;p

**Comment by avg-I** [comment]
I'll add that you may need to set `defaultrouter` in the jail's rc.conf.
Also, if you have not created any bastille vnet jails, then you'd need:
```
install -m 0544 /usr/share/examples/jails/jib /usr/local/bin/jib
```

**Comment by bmac2** [comment]
VNET fully supported today in current release.  Solution above posted to change a jail from non-vnet to vnet. 

Closing.

**Comment by avg-I** [comment]
It still would be nice if bastille had a command (or, at the very least, documentation) on how to do the conversion.
But I guess that internet search and/or likes of ChatGPT are considered good enough these days :slightly_smiling_face:
