### ISSUE TITLE
[ENHANCEMENT] bastille list.sh needs a column for indicating if a jail is running or stopped.

### ISSUE THREAD

**Issue by X86BSD** [BastilleBSD/bastille#192]
I understand that the way it works now a 'bastille list' only lists jails that are running.
Currently there is no way to see in the list output, that I am aware of, if a jail is stopped or if it's available after creation. Say a new admin takes over the box bastille runs on and has no idea what jails were ever created with bastille. All he/she will see is a list of running jails.

Because of this you have no idea what jails need to be started because they are not listed. This makes you wonder if your jail was even created right, or if it got deleted somehow, or for the new person what jails were ever created.

iocage when you do an 'iocage list' has a column that lists 'up' or 'down'.

This is incredibly useful to see an instant output of all running and stopped jails.
If you have a lot of them or even a few, showing only the ones running when doing a 'bastille list' can be.. confusing to those unfamiliar with bastille. 

Personally because of the way iocage set precedence here, and the fact that ifconfig also uses 'up' to indicate an interface is up, I would suggest using 'up' and 'down' respectively.

**Comment by tofazzz** [comment]
I share the request as well and the only way I am aware of to check all the jails created in the system is to use the "bastille list containers" command and it will give you a raw list off all the jails configured.

**Comment by JRGTH** [comment]
Does something like this simple status listing is enough?:

![image](https://i.imged.com/i-80156525.png)

**Comment by X86BSD** [comment]
So I think that looks fine, but it's not complete IMO. What's missing for me is a column indicating 'up' or 'down'.I want to be able to see at a glance with 'bastille list' whether a jail is running or stopped. I don't care if it says 'up' or 'down', or if it says 'running' or 'stopped'. But I need some way upon the output of 'bastille list' to see at a glance which jails are running and which are stopped. Having to use two separate commands 'bastille list' and 'bastille jails' is imo obtuse, overly complicating things, duplicating effort, and makes the UX much more difficult. 

I get the "its just two commands" argument. But from the user perspective it's kind of ridiculous he/she has to issue the same command, one with an extra word on it, to see what is running and what isn't. This should be output in a single column from a singular command 'bastille list'. 

That's just my opinion. 

If you added one more column to your image above JRGTH that showed "up|down" or "running|stopped" it would be ideal.

**Comment by cedwards** [comment]
This is addressed in #376

**Comment by cedwards** [comment]
Considering this addressed by the merge in #376.
