### ISSUE TITLE
[ENHANCEMENT] When bastille creates a jail, it would be very nice to have the interface configured with the 'Description' option set similar to iocage.

### ISSUE THREAD

**Issue by X86BSD** [BastilleBSD/bastille#194]
When bastille creates a a jail and uses a corresponding interface it does not label the interface with the optional 'description' argument. 

Ideally I would prefer to see bastille have the option of creating a unique interface per jail and then setting the description of that interface similar to iocage as such:

vnet0.1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: associated with jail: Bigdata1 as nic: epair0b

When dealing with *a lot* of jails, having them each have their own interface in ifconfig makes it soooo much easier to see information about each jail and unique settings on that jails interface. Having the description line set like above makes debugging and dealing with a lot of jails exponentially easier because you know from the description line the interface belongs to a jail, what the jails name is, etc

It's just incredibly helpful to the end user and gives more information when they need it for debugging or figuring out what goes where jail wise.

**Comment by bmac2** [comment]
@cedwards is this still on the roadmap since you assigned it to yourself?

@X86BSD could you attach a screenshot or the output of what iocage shows so I understand what it is we are trying to mimic please?

**Comment by bmac2** [comment]
![image](https://github.com/BastilleBSD/bastille/assets/7692139/8d5196da-4e55-46ac-a542-c9a9ed30d364)

**Comment by bmac2** [comment]
@X86BSD per @cedwards the io cage style descriptions are there.  Is the current way sufficient or is there still something missing that you are looking for??

**Comment by X86BSD** [comment]
I need to find the time here soon to sit down and reread my enhancement and
read the replies. I’ll try to squeeze some time this weekend to catch up on
this issue so you can close it.

**Comment by cedwards** [comment]
We've got this now. Closing.

Example:
```
e0a_bastille10: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: vnet host interface for Bastille jail 01-vnet-clone
	options=8<VLAN_MTU>
	ether 02:90:7c:ae:5f:70
	hwaddr 02:d1:90:4d:4d:0a
	groups: epair
	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```
