### ISSUE TITLE
[BUG] bastille should not be logging to /usr/local/bastille/logs 

### ISSUE THREAD

**Issue by X86BSD** [BastilleBSD/bastille#195]
I'm not sure why this was set this way, im sure there was a reason, but this breaks hier(7), POLA, and no one will know to look in /usr/local/bastille/* for anything log related. They will go to /var/log/ and be really confused.

My suggestion is to change the logging directory to /var/log/bastille/
Since the log files are created with the jails creation name I don't see any reason to make a /var/log/bastille/logs, that would just be needless extra verbosity.

**Comment by cedwards** [comment]
This will be updated in the next release and log to `/var/log/bastille/` as suggested.
