### ISSUE TITLE
[ENHANCEMENT] Use already existing bridge with VNET jail

### ISSUE THREAD

**Issue by GuillaumeBibaut** [BastilleBSD/bastille#199]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I'm not really sure about this use case, but since it happens to me, I'm still wondering if it can happen to anybody else.
I'm using my company's servers to test out some solutions with jails or bhyve, or both on the same server.
While the `jib` tool inside the `share/examples` for jail is really useful for a start, I'm still finding it quite restrictive. This is why I've come to look at the script and to (sort of) find an easier, more distinctive use case with existing bridge.

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.

I've tried to apply a one for all configuration for my VNET jails, but also to be able to use whatever bridge I want, and not be restrict to the `{interface}{bridge}` notation created by the `jib` script.
Here is the `jail.conf` file I'm using:
```
$bridge = "vm-public";
path = "/jails/${name}";
devfs_ruleset = "11";
host.hostname = "${name}.j.my.domain";
allow.set_hostname = 1;
mount.devfs;
exec.clean;
exec.system_user = "root";
exec.jail_user = "root";
exec.start = "/bin/sh /etc/rc";
exec.stop = "/bin/sh /etc/rc.shutdown";
exec.prestart += "ifconfig epair${index} create";
exec.prestart += "ifconfig ${bridge} addm epair${index}a";
exec.prestart += "ifconfig epair${index}a up name e${index}a_${name}";
exec.prestart += "ifconfig epair${index}b up name e${index}b_${name}";
exec.poststop += "ifconfig ${bridge} deletem epair${index}a";
exec.poststop += "ifconfig e${index}a_${name} destroy";
exec.consolelog = "/var/log/jail_${name}_console.log";
vnet;
vnet.interface = "e${index}b_${name}";
yom {
        $index = "0";
        sysvmsg = new;
        sysvshm = new;
        sysvsem = new;
}
```
Many of these parameter are only subjective to what I want, so of course it can be adapted, changed.
In this example, I'm also using bhyve VMs using the `sysutils/vm-bhyve` with which I've created a `public` switch (bridge). I'm declaring this bridge in my global jail configuration, but it could be per jail (in some cases it would apply to).

So I could see a case of use with the `create -V` command where one could pass an additional argument `-B {bridgename}`, where `{bridgename}` would be an already existing bridge.
This configuration could be upgraded to something where the `{bridgename}` could be check if existing or not, or to tell with a `create` command additional argument to create the bridge with an associated interface.
Does this make sense?

> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

No addional alternative for now.

> **Additional context**
> Add any other context or screenshots about the feature request here.

No additional context.

**Comment by woodsb02** [comment]
I'm looking for a solution to this also.

**Comment by agrajag9** [comment]
#513

**Comment by agrajag9** [comment]
We're now >2yrs since this was requested and lack of implementation is creating bugs downstream that are only fixable by recreating jails from scratch or manually fixing confs :(

**Comment by schrodyn** [comment]
For my network design I cannot use BastilleBSD without the feature of being able to bridge jails into existing bridges. My example use case is an existing hosting VLAN that I want to add jails in out. Would definitely see this as a huge feature benefit. Thanks for all your work on the project but would love to see this feature finally implemented as it's currently a blocker for me to use BastilleBSD for jail management.

**Comment by woodsb02** [comment]
It looks like this feature was added in on 2nd December 2021, and included in the Bastille release 0.9.20211225 "Happy Holidays".
Refer to commits ec1356d and d951a70.
Refer to release notes: https://github.com/BastilleBSD/bastille/releases/tag/0.9.20211225
I believe this feature request can now be closed?

**Comment by schrodyn** [comment]
The feature exists but there are also open issues with it. Please see https://github.com/BastilleBSD/bastille/issues/516 and https://github.com/BastilleBSD/bastille/issues/513 BastilleBSD had issues adding multiple jails to an existing bridge as it seems to always pick the said epair interface ID.

**Comment by zilti** [comment]
Nonetheless that means this issue here should be closed.

**Comment by cedwards** [comment]
This is now supported with `bastille create -B` providing the existing bridge name as the final create option. Closing.

**Comment by agrajag9** [comment]
@cedwards Could you share the commit for reference? I wasn't able to find it myself.

**Comment by tobiastom** [comment]
@agrajag9 I think the feature was implemented here: https://github.com/BastilleBSD/bastille/commit/ec1356df082a6afe97a10570d6d4611198581a23 and documented here https://github.com/BastilleBSD/bastille/commit/ec1356df082a6afe97a10570d6d4611198581a23.
