### ISSUE TITLE
[BUG] Permission error on first bootstrap

### ISSUE THREAD

**Issue by mariusvw** [BastilleBSD/bastille#208]
When bootstrapping the first release you run into the following error
```
# bastille bootstrap 12.1-RELEASE                                                                                 
Insecure permissions on /usr/local/bastille
Try: chmod 0750 /usr/local/bastille
```

Versions
```
# bastille -v && freebsd-version -kru
0.6.20200202
12.1-RELEASE-p3
12.1-RELEASE-p3
12.1-RELEASE-p3
```

Installed from PKG, configured using ZFS.

This should be fixed in the Makefile of the ports or add an extra check on the first bootstrap to correct the permissions.
My preference would be the Makefile.

https://svnweb.freebsd.org/ports/head/sysutils/bastille/Makefile?view=markup&pathrev=531607

**Comment by mariusvw** [comment]
Seems to be resolved in #177

**Comment by zilti** [comment]
Pretty sure that is fixed now, no? At least this never happened to me.

**Comment by ryanavella** [comment]
@zilti I'm seeing this as well when trying to bootstrap bullseye, so I don't think so. I also installed from PKG and configured using ZFS.

**Comment by bmac2** [comment]
@mariusvw @ryanavella   is this still an issue?  If it is please put the steps for me to recreate so I can evaluate how to fix.  

@cedwards  do you know of this still an issue or is it an old issue.  Originally opened in early 2020

**Comment by bmac2** [comment]
This was fixed some  time ago.   If this reoccurs please open a new ticket with details.
