### ISSUE TITLE
[ENHANCEMENT] add basic test to default resolv.conf / check for localhost resolvers

### ISSUE THREAD

**Issue by cedwards** [BastilleBSD/bastille#225]
**Is your feature request related to a problem? Please describe.**
Bastille will use the host resolv.conf but sometimes that isn't ideal.

**Describe the solution you'd like**
Bastille should check for localhost/127.0.0.1/etc within the resolv conf and provide an alternative.

**Describe alternatives you've considered**
just documenting the idea

**Additional context**
this will be useful for cloud instances where providers have customized base

**Comment by bmac2** [comment]
@cedwards is this one still valid?? if so we need to disucss so I understand the ask better.
