### ISSUE TITLE
[BUG] Bastille does not forward error exit codes

### ISSUE THREAD

**Issue by Shadow53** [BastilleBSD/bastille#226]
**Describe the bug**
Certain bastille subcommands exit with a successful exit code despite failing. The bug report is particularly because of the `bastille cp` command, though the issue may be for others as well.

**Bastille and FreeBSD version**
```
$ sudo bastille -v && freebsd-version -kru
0.6.20200414
12.1-RELEASE-p6
12.1-RELEASE-p6
12.1-RELEASE-p6
```

**How did you install bastille? (port/pkg/git)**
Bastille was installed from packages using the `latest` repo.

**Steps to reproduce?**
Create a bastille jail. I made a thick jail of 12.1-RELEASE. Attempt the `bastille cp` command using a nonexistent file as the source and/or a destination with a nonexistent directory. Then `echo $?` to view the exit code.

**Expected behavior**
I expected the exit code to be `1` (or whichever other non-zero values `cp` uses on error).

**Screenshots**
```
$ sudo bastille cp test .login /nonexists/test/test
[test]:
cp: /usr/local/bastille/jails/test/root//nonexists/test/test: Not a directory

$ echo $?
0
$ sudo bastille cp test /nonexists/test/test /root/test
Password:
[test]:
cp: /nonexists/test/test: No such file or directory

$ echo $?
0
```

**Comment by cedwards** [comment]
Thank you for reporting this. I'll look into improving this in the upcoming release.

**Comment by JRGTH** [comment]
This can be done by `return 1` if cp or x command fail, but since returning 1 breaks the batch/loop if one of the jails fails the command, by referencing `false` instead will allow the loop to finish regardless.

This has been improved in [this PR](https://github.com/BastilleBSD/bastille/pull/229/commits/709f00a2ac8a9d5758a04ff649e3728cc4a5193f).

**Example behavior on cmd failure:**

**On single jail:**
```
root@nas-mserver: ~# bastille cp emby .profile_ /media/
[emby]:
cp: .profile_: No such file or directory

root@nas-mserver: ~# echo $?
1
```

**On multiple jails:**
```
root@nas-mserver: ~# bastille cp ALL .profile_ /media/
[emby]:
cp: .profile_: No such file or directory

[test]:
cp: .profile_: No such file or directory

root@nas-mserver: ~# echo $?
1
```

Regards

**Comment by Shadow53** [comment]
Better for a single jail IMO would be to capture the exit code itself and report it after any other commands are run. That way any codes that are not 0 or 1 can be properly detected.

For `ALL`, showing the exit code in the output could be useful? 🤷‍♂️ Not sure about that. For that case, returning `1` on any failure seems more appropriate.

**Comment by JRGTH** [comment]
Indeed this need some more testing/improvements with single and multiple jails executing and returning different codes other than 0/1, maybe just removing the added line break `echo`which also causes the last status to be always 0 as initially reported here.

Regards

**Comment by JRGTH** [comment]
Hi, considered and tested what you suggested and it seems to be more appropriate indeed, for `cp` batch `ALL`, the return status of said jail/cmd will be displayed for reference, useful for quick spot unsuccessful/non zero cmd executions on the loop, for single jail the exit status will be just captured, also the line break is keep to avoid cluttered output.

[Reference PR](https://github.com/BastilleBSD/bastille/pull/229/commits/a0b0eadc684acc2ba59866e245fe0b3ca00ce7d5).

**Example behavior**
**Multiple jails:**
```
root@nas-mserver: ~# bastille cp ALL myfile /media/myfile
[emby]:
myfile -> /mnt/storage/bastille/jails/emby/root//media/myfile
Returned: 0

[test]:
cp: /mnt/storage/bastille/jails/test/root//media/myfile: No such file or directory
Returned: 1

[test2]:
myfile -> /mnt/storage/bastille/jails/test2/root//media/myfile
Returned: 0

root@nas-mserver: ~# echo $?
0
```

**Single jail:**
```
root@nas-mserver: ~# bastille cp test myfile /media/myfile
[test]:
cp: /mnt/storage/bastille/jails/test/root//media/myfile: No such file or directory

root@nas-mserver: ~# echo $?
1
```

Regards

**Comment by zilti** [comment]
It would be especially handy to have this for the CMD subcommand, making it much easier to use Bastille jails as test environments.

**Comment by zilti** [comment]
Wouldn't it be enough to change the last line in cmd.sh from `return "${RETURN}"` to `exit ${RETURN}`? Or would that break something?

**Comment by zilti** [comment]
Did pull request https://github.com/BastilleBSD/bastille/pull/303 fix this?

**Comment by bmac2** [comment]
@Shadow53 @JRGTH   did #303 fix this issue?  IF not let me know.

**Comment by bmac2** [comment]
303 was merged.  Closing as fixed.
