### ISSUE TITLE
[ENHANCEMENT] 32 Bit Jails?

### ISSUE THREAD

**Issue by gallexme** [BastilleBSD/bastille#227]
**Is your feature request related to a problem? Please describe.**
tried the custom base.txz bootstrap but doesnt seem to work
in /usr/local/bastille/cache i added a RELEASE folder and inside the base.txz of 12.1 32 Bit Freebsd

```bash
mmo# pwd
/usr/local/bastille/cache
mmo# bastille bootstrap
Usage: bastille bootstrap [release|template] [update].
mmo# bastille bootstrap release
Usage: bastille bootstrap [release|template] [update].
mmo# bastille bootstrap RELEASE
Usage: bastille bootstrap [release|template] [update].
mmo# ls
12.1-RELEASE    RELEASE
mmo# ls RELEASE
base.txz
```

**Describe the solution you'd like**
A way to use 32 Bit Jails on 64bit Host/Ovewrite Architecture

**Describe alternatives you've considered**
Ovewritting Architecture

**Additional context**

**Comment by cedwards** [comment]
This is an interesting (new) use case that I haven't considered...

I'm curious if adding `lib32` to the `bastille_bootstrap_archives` is sufficient to provide 32-bit support.

It wouldn't be a 32-bit (only) jail on 64-bit host but it _should_ provide 32-bit binary support in the jail.

**Comment by gallexme** [comment]
i need 32 bit only jail, for pkg installs/compilation toolchains

the only thing i need for that is a way to specify my own base.xz, freebsd native jails work already, focker  also can do that by using your own base.xz ( https://github.com/sadaszewski/focker/#preparing-base-image)

**Comment by gallexme** [comment]
and it should already be supported in bastilleBSD but it doesnt work:

> Advanced: If you want to create your own custom base.txz, or use an unsupported variant of FreeBSD, drop your own base.txz in > cache/RELEASE/base.txz and bastille bootstrap will attempt to extract and use it.

**Comment by cedwards** [comment]
You're right. That should work. Will revisit.

**Comment by JRGTH** [comment]
> and it should already be supported in bastilleBSD but it doesnt work:
> 
> > Advanced: If you want to create your own custom base.txz, or use an unsupported variant of FreeBSD, drop your own base.txz in > cache/RELEASE/base.txz and bastille bootstrap will attempt to extract and use it.


Hi, the "cache/**RELEASE**/base.txz" name was a generalization, you need to define said RELEASE version like **XX.X-RELEASE** as `bastille` validates the name based on supported versions, where XX.X could be 12.1 etc. then drop said custom tarball there, unfortunately this can interfere with an existing RELEASE with same version, and this is what the case may be here.

Alternatively there is an **empty** jail creation feature to create unsupported/customs, however this requires for manual tarball extraction in the `pathto/jails/jail_name/root/` and `jail.conf` adjustments, also note that this custom jails are generally thick as expected.

Here below are the steps to create an 32-Bit jail under a 64-Bit host:
**Host:**
```
root@nas-mserver: ~# uname -a
FreeBSD nas-mserver.xyz 12.1-RELEASE-p7 FreeBSD 12.1-RELEASE-p7 GENERIC  amd64
```

**Create an empty jail:**
```
root@nas-mserver: ~# bastille create -E 32_bit
Creating empty jail: 32_bit.
```

**Check the empty jail mountpoint:**
```
root@nas-mserver: ~# mount | grep "32_bit"
storage/bastille/jails/32_bit on /mnt/storage/bastille/jails/32_bit (zfs, local, noatime, nfsv4acls)
storage/bastille/jails/32_bit/root on /mnt/storage/bastille/jails/32_bit/root (zfs, local, noatime, nfsv4acls)
```

**CD to the empty jail root:**
```
root@nas-mserver: ~# cd /mnt/storage/bastille/jails/32_bit/root
```

**Fetch the desired RELEASE base:**
```
root@nas-mserver: /mnt/storage/bastille/jails/32_bit/root# fetch http://ftp10.freebsd.org/pub/FreeBSD/releases/i386/12.1-RELEASE/base.txz
base.txz                                               142 MB  275 kBps 08m49s
```

**Extract/clean the base.txz in the jail root:**
```
root@nas-mserver: /mnt/storage/bastille/jails/32_bit/root# tar -xf base.txz && rm base.txz
```

**Edit the container jail.conf to taste(an existing config may be used for reference):**
```
root@nas-mserver: /mnt/storage/bastille/jails/32_bit/root# bastille edit 32_bit jail.conf
~~~
```

**Start the new 32_bit jail:**
```
root@nas-mserver: ~# bastille start 32_bit
[32_bit]:
32_bit: created
```

**Verify the new jail architecture:**
```
root@nas-mserver: ~# bastille cmd 32_bit uname -a
[32_bit]:
FreeBSD 32_bit 12.1-RELEASE-p7 FreeBSD 12.1-RELEASE-p7 GENERIC  i386
```

Here are the FreeBSD RELEASES for reference:
[pub/FreeBSD/releases](http://ftp10.freebsd.org/pub/FreeBSD/releases/)

Note that the above is provided as is and is still unsupported.
 
Regards

**Comment by JRGTH** [comment]
Hi, a PR has been added for [initial support for 32-Bit jails creation](https://github.com/BastilleBSD/bastille/pull/229).
Regards

**Comment by cedwards** [comment]
Confirm this can be closed now?

**Comment by JRGTH** [comment]
Yes it can be closed, since a PR has been added for **initial** support for 32-Bit jails creation to avoid the manual/empty jail hassle.
Regards
