### ISSUE TITLE
[ENHANCEMENT] BBB and NextCloud bastille-template

### ISSUE THREAD

**Issue by zenny** [BastilleBSD/bastille#235]
Hi,

It would be extremely useful if you add  

1. bigbluebutton template for `bastille`, based on latest version of bbb (https://docs.bigbluebutton.org/2.2/install.html) and 
2. NextCloud template.

Cheers,
/z

**Comment by cedwards** [comment]
Does not appear that bbb is supported under FreeBSD.
Nextcloud appears current per freshports; will look into that as a template.
