### ISSUE TITLE
[ENHANCEMENT] Install a port instead of a package?

### ISSUE THREAD

**Issue by lifepillar** [BastilleBSD/bastille#238]
I want a customized installation for some packages, as it can be obtained by compiling them from ports. What are the best practices (if any) to install from ports using Bastille?

The [documentation](https://bastille.readthedocs.io/en/latest/chapters/template.html#template-automation-hooks) mentions that `PKG`'s format supports “port/pkg name(s)”, but how AFAICS you can use it only to install packages.

**Comment by tobiastom** [comment]
Right now I'm compiling custom packages and create a private package registry from it, before provisioning a new jail. The jail itself then contains a this registry and I can install them with `pkg`.

This has the advantage that the packages do not need to be compiled for every jail, but it's not very nice to manage.

Seeing improvements here would be nice.

**Comment by fibric** [comment]
`pkg` doesn't install most recent `erlang@23` version instead `pkg` install `erlang@21`. I wish I could easily install `erlang` via ports.

**Comment by bmac2** [comment]
Duplicate with item #157 
Closing to track on item #157
