### ISSUE TITLE
[BUG?] Sendmail is disabled in jails, with no replacement

### ISSUE THREAD

**Issue by lifepillar** [BastilleBSD/bastille#240]
Bastille currently shuts off Sendmail in each jail (see also: https://github.com/BastilleBSD/bastille/issues/212). But according to [FreeBSD Handbook,  §28.4](https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/mail-changingmta.html), a system should have a functional MTA.

Using `sendmail_enable="NO"` (only) should be better than completely disabling Sendmail, because that would only disable the incoming mail service (see `man rc.sendmail`).

IMO, however, for jails it would be better to have Sendmail replaced by DMA (which is in base), configured to deliver mail locally (which should be the default). Then, it would be an easy task for a user to update `dma`'s configuration in a jail to, say, have email forwarded to a centralized host.

The reason why I think `dma` is better is that it can only accept email locally by design, and it runs no services. It may also be easier to configure than `sendmail` for most users (`man dma`).

I *think* that, in addition to shutting off Sendmail, disabling Sendmail-specific tasks (as explained in the handbook) and updating `/etc/mail/mailer.conf` to use `dma` would be enough, but I have not fully tested that.

I have installed bastille with `pkg`:

```
bastille -v && freebsd-version -kru
0.6.20200414
12.1-RELEASE-p8
```

**Comment by yerrysherry** [comment]
I think it is not the job of Bastille to configure an other MTA like DMA. That is the job of the sysadmin. The reason to turn off mail is to have no messages in the mail queue and don't waste disk space.

Normally "periodic" runs every day from cron and takes a lot of resources, like cpu, disk IO  ... and now we never see the output. 

As a simple test: 

$ date ; time periodic daily ; date
Tue Jan  5 13:12:47 CET 2021
83.592u 119.318s 3:22.95 99.9%	978+192k 1537522+641io 6pf+0w
Tue Jan  5 13:16:10 CET 2021

If you want to see the output, change "/etc/periodic.conf" 

$ cat /etc/periodic.conf
daily_output=/var/log/daily.log

That is nearly 4 minutes for one jail (in my case). Suspose you have 30 jails. Your system will become slow after 3am. Also take a look at "/var/log/daily.log". You will find a lot of the same info in daily.log and some parts are also not relevant, like the uptime

I think it is better to update the documentation and write a little section like "What to do after creating a jail"

**Comment by bmac2** [comment]
@cedwards  do we want to do anything on this??  to me, imho, if a person wants an MTA they can template it into a jail.  I don't think we want to manage all the various MTAs on all jails.

**Comment by adriel-tech** [comment]
The current default makes sense, users can setup MTAs using their own templates with minimal effort.

**Comment by bmac2** [comment]
closing as will not do since a  template for a mail server has been provided.
