### ISSUE TITLE
[ENHANCEMENT] Document workflow for how to make changes to files inside jail

### ISSUE THREAD

**Issue by zachfi** [BastilleBSD/bastille#252]
I'm a little confused about the intended workflow for using this project.  In particular, a guide on how I would make changes to a file within the jail based on some kind of external data would be useful.  Templates seem like they would help here, but I can't tell if that's where the specific instance of a config would live.

Specifically thinking about how I would configure an NSD or Unbound configuration that might have some site-specific details in it.

**Comment by tobiastom** [comment]
Right now you would have to put the real values into the templates. If you use an existing one, you would need to fork it and apply your changes.

In the future you might be able to use arguments for the template command (see #211 for more details).

**Comment by bmac2** [comment]
Documentation was updated multiple times since this ticket was put in.  

closing.
