### ISSUE TITLE
[BUG] VNET Jails default gateway is wrong

### ISSUE THREAD

**Issue by PetruGarstea** [BastilleBSD/bastille#263]
**[MANDATORY] Describe the bug [MANDATORY]**
FreeBSD host acts as an edge gateway and runs jail containers at the same time.

wan interface gets IP dynamically from ISP DHCP
lan ip is static set in rc.conf

VNET Jail default route is set wrong/typo in rc.conf, that is happening because the setup includes gif0 interface in rc.conf

snippet from rc.conf
```
cloned_interfaces="gif0"
create_args_gif0="tunnel IPv4a IPv4b"
ifconfig_gif0_ipv6="inet6 bla:bla:bla:bla prefixlen 128"
ipv6_defaultrouter="-iface gif0"
```

reproducing the issue
```
# bastille create --vnet test 12.1-RELEASE 10.0.0.1 lan
Valid: (10.0.0.1).
Valid: (lan).

NAME: test.
IP: 10.0.0.1.
INTERFACE: lan.
RELEASE: 12.1-RELEASE.

syslogd_flags: -s -> -ss
sendmail_enable: NO -> NO
sendmail_submit_enable: YES -> NO
sendmail_outbound_enable: YES -> NO
sendmail_msp_queue_enable: YES -> NO
cron_flags:  -> -J 60
ifconfig_e0b_bastille2_name:  -> vnet0
ifconfig_vnet0:  -> inet 10.0.0.1
defaultrouter: NO -> here is WAN IP
gif0
```

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.7.20200714
12.1-RELEASE-p10
12.1-RELEASE-p10
12.1-RELEASE-p10

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg

**[optional] Steps to reproduce?**
N/A

**[optional] Expected behavior**
now
```
# bastille cmd test cat /etc/rc.conf
[test]:
syslogd_flags="-ss"
sendmail_enable="NO"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"
cron_flags="-J 60"
ifconfig_e0b_bastille2_name="vnet0"
ifconfig_vnet0="inet 10.0.0.1"
defaultrouter="here is wan ip
gif0"
```
expect
```
# bastille cmd test cat /etc/rc.conf
[test]:
syslogd_flags="-ss"
sendmail_enable="NO"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"
cron_flags="-J 60"
ifconfig_e0b_bastille2_name="vnet0"
ifconfig_vnet0="inet 10.0.0.1"
defaultrouter="inet 10.0.0.254" # LAN default gateway 
```

**[optional] Screenshots**
N/A

**[optional]  Additional context**
N/A

**Comment by cedwards** [comment]
Bastille attempts to auto-detect the default gateway if not defined in the bastille.conf.

If you define `bastille_network_gateway=` in the config your VNET jails should be assigned that address as gateway.

Looks like our auto-detection is failing on your slightly more complex network.

**Comment by PetruGarstea** [comment]
confirming with the definition `bastille_network_gateway=` works as expected

**Comment by cedwards** [comment]
I'll see about improving the VNET documentation to recommend setting this value if needed.
