### ISSUE TITLE
bastille cmd exit code not respected

### ISSUE THREAD

**Issue by mcgaw** [BastilleBSD/bastille#272]
Describe the bug
The exit code from the command run using `bastille cmd` is not respected.

Bastille and FreeBSD version
0.7.20200714
12.2-STABLE
12.2-STABLE
12.2-STABLE

How did you install bastille?
github

Steps to reproduce
`bastille cmd my_container more xxxx`
`echo $?`

Expected behavior
Output of 1 on console. 0 is output.

**Comment by zilti** [comment]
Did pull request  #303 fix this for you?

**Comment by mcgaw** [comment]
Hi, I've quickly tested it and the issue now appears resolved. Sorry for not keeping an eye on it but I switched to iocage not long after raising this issue since it appeared more mature and satisfied broadly the same use cases. Not sure how things have evolved since then.
