### ISSUE TITLE
[WISHLIST] Features/fixes I'd like to see

### ISSUE THREAD

**Issue by cedwards** [BastilleBSD/bastille#295]
Priority list of projects / tasks for Bastille:

1. capture exit codes (#226 / #272 )
2. add debug option and output / output exit codes (extends #278 )
3. extend/validate template to support use bootstrap/create/destroy/etc subcommands
4. extend/validate template changes to RELEASE targets 
5. configurable pf table name in config (currently <jails>, should be <bastille> by default)

**Comment by zenny** [comment]
@cedwards 

I love to see something like k3s orchestration and provisioning (https://github.com/techno-tim/youtube-videos/tree/master/k3s-ha-install) in FreeBSD (also see #234). 

Cheers,

**Comment by hackacad** [comment]
#324

**Comment by bmac2** [comment]
@cedwards can you close this one and if  there are still things you want to see put them in one per ticket into backlog for  me.
