### ISSUE TITLE
OVERLAY in Bastillefile

### ISSUE THREAD

**Issue by crypto-scythe** [BastilleBSD/bastille#299]
**Describe the bug**
Maybe I understood it wrong but it seems to me that OVERLAY is not supported inside Bastillefile?

The OVERLAY directive does not work inside a Bastillefile (Help gets output and after that "Failed to execute command:"). But adding an OVERLAY file to the template folder does work, but the files get overlayed after the Bastillefile commands ran. 

My use case is that I need to have files in place before running specific commands. In this scenario I have some port configurations that need to be present before I run the make commands for them.

**Bastille and FreeBSD version**
0.7.20200714
12.1-RELEASE-p11
12.1-RELEASE-p11
12.1-RELEASE-p12

**How did you install bastille? (port/pkg/git)**
pkg

**[optional] Steps to reproduce?**
Put OVERLAY foldername in Bastillefile e.g.

```
CMD echo 'Runs'
OVERLAY root
CMD echo 'Never runs'
```

Output is
```
[mail]:
Applying template: chris/test...
[mail]:
Runs

Bastille is an open-source system for automating deployment and management of
containerized applications on FreeBSD.

Usage:
  bastille command TARGET [args]

Available Commands:
  bootstrap   Bootstrap a FreeBSD release for container base.
  ...

Use "bastille -v|--version" for version information.
Use "bastille command -h|--help" for more information about a command.

Failed to execute command:
```

**[optional] Expected behavior**
The OVERLAY directive should run in Bastillefile between the other commands

**[optional] Screenshots**

**[optional]  Additional context**

**Comment by chriswells0** [comment]
The Bastillefile syntax uses Bastille subcommands (without the target), so you can use `CP` instead:
```
CP root /
```

**Comment by crypto-scythe** [comment]
Thanks, now the error message makes sense :)
