### ISSUE TITLE
Port upgrade

### ISSUE THREAD

**Issue by josejachuf** [BastilleBSD/bastille#315]
When will the port be updated in freebsd to 0.8.x?

**Comment by cedwards** [comment]
The update to ports has been submitted here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252745

`0.8.20210115` is the release version.

**Comment by josejachuf** [comment]
Thanks @cedwards 

One more question about version 0.8.x. I have some cages created with version 0.7.x in production (I don't use templates). What considerations should I have when migrating? Can you break me something? I understand that nothing should happen, but just to be safe.

Jose

**Comment by cedwards** [comment]
The primary things to be aware of are a few updates to the `bastille.conf` (related to default template paths). 

These default templates should only apply to NEW containers, so existing should be untouched. Also, the defaults in the base templates apply the same config as 0.7, just using the template system to do so.

See release notes for full details on the changes:
https://github.com/BastilleBSD/bastille/releases/tag/0.8.20210115
https://github.com/BastilleBSD/bastille/releases/tag/0.8.20210101
