### ISSUE TITLE
[BUG] `bastille start ALL` not respecting bastille_list

### ISSUE THREAD

**Issue by hackacad** [BastilleBSD/bastille#318]
**[MANDATORY] Describe the bug [MANDATORY]**
`bastille start ALL` does not recognise bastille_list in rc.conf

I'd expect the same behaviour as in `service bastille start`
Other options would be adding a `bastille start ENABLED` or something like `bastille start -f ALL / bastille start --no-list-file ALL`.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
 bastille --version && freebsd-version -kru

> 0.8.20210115
> 12.2-RELEASE-p1
> 12.2-RELEASE-p1
> 12.2-RELEASE-p2

**[MANDATORY] How did you install bastille? (port/pkg/git)**
port

**[optional] Steps to reproduce?**
rc.conf
> bastille_list+=testjail sysrc bastille_list-=oldjail
Bastille start ALL
[oldjail]:
oldjail: created

**Comment by bmac2** [comment]
@hackacad is this still an issue?  Let me know if it is still an issue, or did this get fixed in subsequent releases.

**Comment by tobiastom** [comment]
I think it is. In [start.sh](https://github.com/BastilleBSD/bastille/blob/master/usr/local/share/bastille/start.sh#L55) `bastille list jails` is executed to get the list of all jails. 
In [list.sh](https://github.com/BastilleBSD/bastille/blob/master/usr/local/share/bastille/list.sh) there is no usage of `bastille_list`.

**Comment by bmac2** [comment]
The ALL target was not designed to be tied to bastille_list.  ALL means what it says, ALL jails.  The option for the Bastille_list was designed for boot time only.

Closing as works as designed.
