### ISSUE TITLE
pf.conf sample file is incorrect or incomplete

### ISSUE THREAD

**Issue by zilti** [BastilleBSD/bastille#320]
I've set up a VM using Vagrant, installed Bastille inside, set up the networking, and copied the example pf.conf. I ended up with this pf.conf:
```
vagrant@:~ $ cat /etc/pf.conf 
ext_if="vtnet0"

set block-policy return
scrub in on $ext_if all fragment reassemble
set skip on lo

table <jails> persist
nat on $ext_if from <jails> to any -> ($ext_if:0)

## static rdr example
# rdr pass inet proto tcp from any to any port {80, 443} -> 10.17.89.45

## Enable dynamic rdr (see below)
rdr-anchor "rdr/*"

block in all
pass out quick keep state
antispoof for $ext_if inet
pass in inet proto tcp from any to any port ssh flags S/SA keep state
pass in inet proto tcp from any to any port nfs flags S/SA keep state
pass in inet proto tcp from any to any port {80, 443} flags S/SA keep state

## make sure you also open up ports that you are going to use for dynamic rdr
# pass in inet proto tcp from any to any port <rdr-start>:<rdr-end> flags S/SA keep state
# pass in inet proto udp from any to any port <rdr-start>:<rdr-end> flags S/SA keep state
```

And this jail config:
```
vagrant@:~ $ sudo bastille list
 JID             IP Address      Hostname                      Path
 devbox          10.0.0.3        devbox                        /usr/local/bastille/jails/devbox/root
vagrant@:~ $ sudo bastille rdr devbox list
rdr pass on vtnet0 inet proto tcp from any to any port = 5432 -> 10.0.0.3 port 5432
rdr pass on vtnet0 inet proto tcp from any to any port = 80 -> 10.0.0.3 port 80
rdr pass on vtnet0 inet proto tcp from any to any port = 443 -> 10.0.0.3 port 443
```

There's a caddy server running inside the devbox jail. I can reach it both from inside the jail and from the vm, but not from outside. Same happens when I use nginx instead, so the actual webserver can be ruled out. The VM config can be ruled out as well, since it works fine when I run the webserver directly in the VM instead of in a Bastille jail.

Trying to connect with lynx from the host machine ends with a "Unable to make secure connection to remote host." when trying to connect via HTTPS, and with an "Unexpected network error" when trying just HTTP.

Which leads me to the conclusion that there's something missing in that pf.conf file.

**Comment by hackacad** [comment]
Can you check:
(1) host# `pfctl -T show -t jails` 
does is contain your jails‘ IP address? (this tables is dropped on pf restart)
(2) are you using double NAT? Remove the `antispoof` rule in pf.conf for testing

**Comment by zilti** [comment]
It does contain the IP address, and for the second, thanks, I removed that for now. I tried this: https://forums.freebsd.org/threads/pf-redirect-ports.62212/#post-359240 but without success.

**Comment by hackacad** [comment]
FTR: you’re trying to connect to http://host_ip not the jails IP correct? 

when trying to connect from host-> jail you would need another rule (pass in on jail_ip proto tcp from host_ip/ext_if). 
RDR is just for NAT, so you have to connect to the hosts IP address

**Comment by zilti** [comment]
Yes, correct. Connecting from the host to the jail works fine (by using the jail IP of course). Connecting from the outside to the host IP and expecting a response from the jail though is what fails.

**Comment by hackacad** [comment]
I just tested everything on a fresh box. Everything works as expected. (I was able to connect to the jail from another PC)

> python3 -m http.server --bind 10.0.0.3 80
> Serving HTTP on 10.0.0.3 port 80 (http://10.0.0.3:80/) ...
> 10.10.10.27 - - [23/Jan/2021 14:55:16] "GET / HTTP/1.1" 200 -

I noticed that you didn't uncomment the following lines
```
## make sure you also open up ports that you are going to use for dynamic rdr
pass in inet proto tcp from any to any port 80 flags S/SA keep state
[...]
```
Did you open up the corresponding port(s)?

**Comment by zilti** [comment]
I did open the ports, yes. Hm. Apparently it had something to do with how Vagrant handles ports. I managed to fix it, the pf.conf was correct after all :)
