### ISSUE TITLE
[QUESTION] vlans

### ISSUE THREAD

**Issue by ghost** [BastilleBSD/bastille#323]
Just curious how I would go about doing vlans with bastille.

Is it just a matter of setting up a vnet jail and assinging the correct vlan interface from host system? Like for example.
```

$ sysrc ifconfig_em1="up" # not sure this is required or not?
$ sysrc vlans_em1="20"
$ sysrc ifconfig_em1_20="up" # or this?
$ sysrc cloned_interfaces="bridge2"
$ sysrc ifconfig_bridge2="addm em1.20 up"

$ bastille create -V foobar 12.2-RELEASE 192.168.20.50/24 em1.20

```

**Comment by miker** [comment]
I was wondering this myself. Any help here would be appreciated.

**Comment by scruffydan** [comment]
I am also wondering this

**Comment by XJOJIX** [comment]
have anyone tried?

**Comment by gregf** [comment]
@XJOJIX I gave it a quick go, but didn't get it working.

**Comment by XJOJIX** [comment]
@gregf bastille will create bridge for you, so you shouldn't have to created it yourself.
try this.
```
$vlans_em1="VLANNAME"
$create_args_VLANNAME="vlan 10"
$ifconfig_VLANNAME="inet 10.0.0.1/24"

$ bastille create -V foobar 12.2-RELEASE 192.168.20.50/24 VLANNAME
```

then follow the BastilleBSD documents for VNETS
```
## /etc/devfs.rules (NOT .conf)
[bastille_vnet=13]
add path 'bpf*' unhide
```

```
$sysctl net.link.bridge.pfil_bridge=0
$sysctl net.link.bridge.pfil_onlyip=0
$sysctl net.link.bridge.pfil_member=0
```
and try to restart your jail

I think jails default ipfw rules is set to DENY from ALL, make sure you check your jails firewall setting.

give me a feedback how it went.

**Comment by hackacad** [comment]
Just ftr:
You don't need VNET for that.

## /etc/rc.conf
```
vlans_em1="VLANNAME"
create_args_VLANNAME="vlan 10"
ifconfig_VLANNAME="inet 192.168.20.49/24"

$ bastille create foobar 12.2-RELEASE 192.168.20.50/24 VLANNAME
```
will work as well.

**Comment by XJOJIX** [comment]
@hackacad 
but that's just using ip
alias isn't it?

if you want to each jail to controll it's own firewall, you still have to create with vnet option.

**Comment by hackacad** [comment]
Correct, missed the original request. This was supposed to be in reply to your message (just an FTR as this looks like the only VLAN issue[QUESTION]).

If you want a full network stack you have to create a VNET jail.

**Comment by bmac2** [comment]
question answered.  Closing.
