### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mikaelmoutakis** [BastilleBSD/bastille#332]
**[MANDATORY] Describe the bug [MANDATORY]**
`bastille service ALL -R` results in an error message. `service -R` is a valid command. 
Of course, I could run `bastille cmd ALL service -R`, but  `bastille service ALL -R` used to work. 

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115, 12.1-RELEASE

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg

**[optional] Steps to reproduce?**
See first topic 

**[optional] Expected behavior**
`bastille service [JAIL] -R` should restart all enabled local services in the jail.

**Comment by cedwards** [comment]
Thank you for reporting this.
Simple matter of number of allowed/required arguments.

**Comment by zilti** [comment]
Shouldn't this issue be closed now that a fix got merged?
