### ISSUE TITLE
[BUG] Variables set with ARG do not seem to propagate when using INCLUDE.

### ISSUE THREAD

**Issue by Hukadan** [BastilleBSD/bastille#335]
**Describe the bug**
Variables set with ARG do not seem to propagate when using INCLUDE.

**Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115
12.2-RELEASE-p1
12.2-RELEASE-p1
12.2-RELEASE-p2

**How did you install bastille? (port/pkg/git)**
Bastille installed with pkg

**Steps to reproduce?**
Step 1 : Define a variable with ARG in a first template (e.g. https://github.com/Hukadan/variables-btemplate/blob/main/Bastillefile)
Step 2 : Use the variable in a second template after including the first template defined in step 1 (e.g. https://github.com/Hukadan/lastest-cache-btemplate/blob/main/Bastillefile). 

**Expected behavior**
Expected behaviour: the variable is available in the second template (e.g. the RENDER function replaces the variable by its value).

Observed behaviour: the variable is not replaced by its value.

Note: the second template works if the variable is defined directly in it.

**Additional context**
I would like to use variables across multiple templates. I thought INCLUDE would be the way to go.

**Comment by tobiastom** [comment]
If I remember correctly it should work in a little more verbose way:

```
INCLUDE sample/template --arg VARIABLE=${VARIABLE}
```

I like that it is more explicit about what will be available to the include, but I can also see why it might be better to reuse all variables.

**Comment by Hukadan** [comment]
I see. I expected INCLUDE to work the other way around. In your example, I should INCLUDE my second template in my first template together with using `--arg` to pass the values of the variables along. What would be the best way to define variables that one wants to use across different templates? With the above, I don't see how to achieve this.
Thanks

**Comment by tobiastom** [comment]
Not sure if I understand your question correctly, but if you combine the above `INCLUDE` with the following Bastille call to apply a template, you would have the variables available in both of them.

Your `sample/first` `Bastillefile`:
```
INCLUDE sample/second --arg NAME=${NAME}

echo ${NAME}
```

The `Bastillefile` for `sample/second `:
```
echo ${NAME}
```

and you would call it with: `bastille template myjail sample/first --arg NAME=tobias`.

Hope this helps, even if not properly tested if this indeed works as expected.

**Comment by Hukadan** [comment]
I am sorry, I did not have time to respond before. Here is my use case. I have a first template for unbound. This template needs at least the following variable:
* the ip address of the unbound jail;
* the ip address and hostname of a pkg cache server.

Then I have a second template for a browser jail. This jail needs at least the following variables:
* the ip address of the unbound jail (for DNS resolution);
* the hostname of the pkg cache (for FreeBSD.conf).

My initial thought was to make a template with all the variables and then use them by including said template in various other templates (here the unbound template and the browser template) so I had to change them in just one place.

I don't see how this is possible with INCLUDE now that you explained how it works with variables.

Thanks for the explanation. I will close this issue since it is clearly not a bug but a misunderstanding on my part.

**Comment by tobiastom** [comment]
@Hukadan there is only way you could archive this: `template` also knows about the `--arg-file` parameter. With that one you don't need to create a separate template, but only a simple file that will contain all your variables. This one you could easily reuse within each `INCLUDE` statement inside the `Bastillefile`. 

Hope this helps. :)
