### ISSUE TITLE
[ENHANCEMENT] Fix binaries inside jail when base host is in a different major release

### ISSUE THREAD

**Issue by fzipi** [BastilleBSD/bastille#339]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when installing a jail in a different major release, because the base kernel will prevent the usage of some commands on the jail.

An example is when a base host is running 12.x, and creating an 11.x jail. Commands like `netstat`, `sockstat` and others that interface with the kernel won't work.

What we normally do is just copy the command binary from the base host to the jail. E.g.:

```bash
root@jail:~ # netstat -an
Some tcp sockets may have been deleted.
Some udp sockets may have been deleted.
Some ip sockets may have been created or deleted.
Some icmp sockets may have been created or deleted.
Some igmp sockets may have been created or deleted.
Some pim sockets may have been created or deleted.
Some ip6 sockets may have been created or deleted.
Some icmp6 sockets may have been created or deleted.
Active UNIX domain sockets
Address          Type   Recv-Q Send-Q            Inode             Conn             Refs          Nextref Addr
               0 #0          0      0           bdca54                0                0                0
Bus error
root@jail:~ # logout
(log in to base host)
root@base-host:~ # cd /usr/local/bastille/releases/1
11.3-RELEASE/ 11.4-RELEASE/ 12.1-RELEASE/ 
root@base-host:~ # cd /usr/local/bastille/releases/11.4-RELEASE/usr/bin/
root@base-host:/usr/local/bastille/releases/11.4-RELEASE/usr/bin # rm netstat 
root@base-host:/usr/local/bastille/releases/11.4-RELEASE/usr/bin # cp /usr/local/bastille/releases/12.1-RELEASE/usr/bin/netstat .
root@base-host:/usr/local/bastille/releases/11.4-RELEASE/usr/bin # logout
(login to jail again)
[root@jail ~] $ netstat -an
Active Internet connections (including servers)
Proto Recv-Q Send-Q Local Address          Foreign Address        (state)    
tcp4       0     36 xx.yy.zz.aa.22      aa.bb.cc.dd.45998    ESTABLISHED
....
```

**Describe the solution you'd like**

Every time a new release is bootstrapped, binaries must be fixed. If the base host is different, then overwrite the files that won't work otherwise.

Maybe also command `bastille fix-binaries <JAIL>` that copies over all commands that won't work on the jail.

Also, it should be called whenever there is an upgrade because things might get overwritten.

**Describe alternatives you've considered**
None other than manually copying what I need, and forgetting to do it each upgrade. Automation is the key.

**Additional context**
None.

**Comment by cedwards** [comment]
This appears to have been fixed in FreeBSD 13+. No issues reported for the past two releases.
