### ISSUE TITLE
[BUG] Bastille bootstrap fails/exits with an error code if the release is already bootstrapped

### ISSUE THREAD

**Issue by KizzyCode** [BastilleBSD/bastille#342]
**[MANDATORY] Describe the bug [MANDATORY]**
Bastille bootstrap fails/exits with an error code if the release is already bootstrapped. This is a problem if the bootstrap is non-interactive (i.e. during Ansible deployments).

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115
12.2-RELEASE-p3
12.2-RELEASE-p3
12.2-RELEASE-p3

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg

**[optional] Steps to reproduce?**
Bootstrap a release using `bastille bootstrap 12.2-RELEASE update` and then bootstrap it again.

**[optional] Expected behavior**
I'd expect that bastille maybe displays a warning (i.e. sth. like "This release is already bootstrapped") but exits with code `0`.
If that is not desired, perhaps an alternative would be to add a switch `--skip-existing` or similar?

**Comment by eoli3n** [comment]
+1 on this as you need to ``|| true`` all commands to be able to automate bastille.

**Comment by chriswells0** [comment]
I'm getting a warning message and exit code 0 on the current master branch. Perhaps this is fixed already but not in packages yet?
```
$ sudo bastille bootstrap 12.2-RELEASE update
Bootstrapping FreeBSD distfiles...
Bootstrap appears complete.

Bootstrap successful.
See 'bastille --help' for available commands.

src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for 12.2-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

No updates needed to update system to 12.2-RELEASE-p8.
No updates are available to install.
$ echo $?
0
```

**Comment by bmac2** [comment]
@KizzyCode is this still broken??  Please advise.

**Comment by bmac2** [comment]
@KizzyCode   bootstrap SHOULD error or at least warn you if the system is already bootstrapped.  Invalidating expected errors just to support ansible scripts makes no sense.  Closing as performs as designed.

cc: @cedwards

**Comment by eoli3n** [comment]
This in not related to ansible at all. If something is already ok, bastille should tell "it's ok". Things beeing as you ask to be is info, not warning/critical.

**Comment by KizzyCode** [comment]
I'm afraid I don't use Bastille/FreeBSD at the moment, so I don't have any horses in the game; but I agree with @eoli3n: if possible, programs should not exit with an error unless something is wrong.

I mean, you could probably argue that wanting to bootstrap if the system is already bootstrapped is wrong, and I see the point behind this logic; however it feels counterintuitive to me because IMO I call this command not to bootstrap per se, but just to _have_ a bootstrapped environment in the end. So as long as there is a valid bootstrapped after the command exits, nothing went wrong from my pov.

P.S.: I think a warning is completely reasonable and makes sense; just not an exit code != 0. 😊
