### ISSUE TITLE
[BUG] Bastille does not work with cbsd jails anymore

### ISSUE THREAD

**Issue by jpoa** [BastilleBSD/bastille#349]
**[MANDATORY] Describe the bug [MANDATORY]**
Bastille used to work fine with cbsd, now after the latest update it does not work.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
bastille -v
0.8.20210115

freebsd-version -kru
12.2-RELEASE-p3
12.2-RELEASE-p3
12.2-RELEASE-p3

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg install bastille

**[optional] Steps to reproduce?**
Run bastille template against a jail created with cbsd. Bastille will complain that the target was not found.

**[optional] Expected behavior**
Bastille should apply the template to the existing jail created with cbsd as it did before the update.

**[optional]  Additional context**
Commenting the check in these lines solved the issue for now (it still fails doing cp later on):
https://github.com/BastilleBSD/bastille/blob/f7ef58cc19aad6400a5f85db6bf59f9d26f56081/usr/local/bin/bastille#L165

**Comment by bmac2** [comment]
@jpoa is this still broken?  If so let me know so we can fix it.
