### ISSUE TITLE
How to set sysctl values when starting a jail using VNET?

### ISSUE THREAD

**Issue by cbunn81** [BastilleBSD/bastille#352]
In the [documentation on networking](https://docs.bastillebsd.org/en/latest/chapters/networking.html), it says that for Virtual Network (VNET) based containers,

> Lastly, you may want to consider these three sysctl values:
>>`net.link.bridge.pfil_bridge=0`
>>`net.link.bridge.pfil_onlyip=0`
>>`net.link.bridge.pfil_member=0`

In my case, I've created a VNET-based container which uses OpenVPN, and it seems that in order for it to work, the above values must be set on the host. But before the container is started, those kernel states are not available as values for sysctl to set, because Bastille creates the bridged interface automatically. If I start my container and then apply those values manually on the host, everything works fine. It would be nice if I didn't have to do this manually each time.

I've tried setting these values in the host's /etc/sysctl.conf, but this doesn't help.

Perhaps using exec.created or exec.poststart in the jail.conf would help?

I think some clarification in the docs would be helpful. Thanks.

**Comment by ddowse** [comment]
Hi,

load the if_bridge.ko module beforehand. 

```bash
kldload if_bridge
systctl -f /etc/sysctl.conf #if you have the obove sysctl's saved in this file
bastille start $TARGET
```

Also consider adding it to /etc/rc.conf to load it if you ever reboot. 

```bash
$EDITOR /etc/rc.conf #add or extend the following line see "man  rc.conf" for furher information
kld_list="if_bridge" #save file
service kld start
```

I hope this solves your problem.

Greetings. 

Daniel

**Comment by XJOJIX** [comment]
can you explain with full example of the files?

**Comment by bmac2** [comment]
solution in comments.  Closing as solved.
