### ISSUE TITLE
[ENHANCEMENT] bastille list should also print release verion

### ISSUE THREAD

**Issue by kkalev** [BastilleBSD/bastille#366]
In a container environment with multiple FreeBSD releases one needs to run freebsd-version inside all containers (with bastille cmd ALL) in order to determine the release version used by each container. It would be very helpful if the information was present in the output of bastille list containers

**Comment by yaazkal** [comment]
I like it. `bastille list` currently prints this:

`JID    IP Address    Hostname    Path`

And you suggesting to print something like this?

`JID    IP Address    Hostname    Path    Release`

**Comment by tofazzz** [comment]
That would be amazing! Also adding if the jail is powered on or off

**Comment by cedwards** [comment]
This is addressed in #376

**Comment by cedwards** [comment]
Considering this resolved with the merge of #376.
