### ISSUE TITLE
[ENHANCEMENT] bastille motion

### ISSUE THREAD

**Issue by kkalev** [BastilleBSD/bastille#367]
This feature request is inspired by the vMotion functionality of the vSphere suite.

BastilleBSD already supports moving containers to a different host by using the export/improt commands. Yet this involves closing a jail for an extended period while export, transfer and import take place.

The suggested feature will leverage ssh and rsync (which must be setup correctly beforehand and is outside the context of BastilleBSD itself).

The suggested command will be **`bastille motion ALL|<container> <new host>`**

 When invoked bastille will do the following:

1. Verify that the destination host has the release needed by the jail installed.
2. rsync the relevant container to the new host **while** the container is still running.
3. Run any additional verifications.
4. Close the jail on the source jailhost
5. Run another rsync round which should only send updates and complete in a very short time.
6. Start jail on destination host. 

An issue will be copying any jail specific limits to the new host.

**Comment by xaque208** [comment]
I'd think there is too much variability and complexity for a feature like this to be generally useful, but perhaps I'm wrong.  Currently, bastille doesn't assume much in the way of how hosts or networks are configured, but for this feature to work properly, I'd think there would need to be significant constraints on the admins to configure the boxes in such a way to allow SSH to move jails.  And in such cases, it would make sense just to have the admin write a script to perform the function needed.

**Comment by bmac2** [comment]
Agree with @zachfi this would cause major limitations on how jails are configured and would eliminate part of the functionality of jails/bastille.   

Closing as will not do.
