### ISSUE TITLE
How to run a script for mount/unmount a NFS Share ?

### ISSUE THREAD

**Issue by Oxyaxion** [BastilleBSD/bastille#371]
Hello,

This is possible to use : `exec_poststart` and `exec_poststop` to run for example a script which un/mount a NFS Share inside a bastille jail in boot / stop.

`exec_poststart="/path/script/nfs_mount.sh 192.168.0.75"`

Example content of the script : 

```
#!/bin/sh
SERVER="${1}"
mount ${SERVER}:/mnt/ztank/my/remote/share /zroot/bastille/myjail/root/mnt/nfs/
```
(It should be possible this is a jail option, but I prefer to ask ...)

Thanks

**Comment by yaazkal** [comment]
You can try the `config` subcommand:

`bastille config TARGET get|set propertyName [newValue]`

In your case:

`bastille config TARGET set exec.poststart '/path/script/nfs_mount.sh 192.168.0.75'`

Of course you need the `nfs_mount.sh` script. I suggest you to look at the templates documentation or examples so you can automate the setting of the property, the restart of the jail, the transfer of the script and even the IP part of the NFS server using Args all in a `Bastillefile`

**Comment by yaazkal** [comment]
This should be labeled as question instead cc @cedwards

**Comment by bmac2** [comment]
Answered by @yaazkal so closing .
