### ISSUE TITLE
[Question] jail startup order

### ISSUE THREAD

**Issue by janondrusek** [BastilleBSD/bastille#389]
Hi! I've been recently playing with Bastille and attempting a "migrate exercise" of my [Docker Compose](https://docs.docker.com/compose/) toy project. Suppose I have 3 Bastille managed jails:

1. MySQL DB exposing port 3306
2. Tomcat App server exposing ports 8080 / 8443
3. Nginx reverse proxy exposing port 80 / 443

I need to start them exactly in the order listed and ports should be available before the next jail starts. Is there a good mechanism to achieve this with Bastille?

Thanks!

**Comment by yaazkal** [comment]
One way of indicating dependencies could be with the `config` subcommand like this:

`bastille config nginx set depend tomcat,mysql`

(guessing your jails have the same name as the service they host).

This way nginx will check if tomcat and mysql are started and if not, it will start them.

So a simble nginx Bastillefile template can look like this:

```
PKG nginx
SYSRC nginx_enable=YES
CONFIG set depend tomcat,mysql
```

Of course you can set the tomcat jail to depend on the mysql jail and then set nginx to depend only on tomcat. Just letting you know that you can set depend to one or more jails.

**Comment by joh-ku** [comment]
One workaround is to use `bastille_list` in `/etc/rc.conf` like:
> bastille_list="jail1 jail2 jail3"

**Comment by pmather** [comment]
I am actually using `bastille_list` as a partial workaround.  I say partial because it doesn't have the same semantics as dependencies have under `iocage`: Bastille will start _and_ stop jails in the order given in `bastille_list` instead of stopping in reverse dependency order.  E.g., if `gitlab` depends upon the `postgresql` jail, I need `postgresql` to be started before `gitlab`.  However, for a clean shutdown, I need `gitlab` shut down before `postgresql`.

So, a complete solution ideally needs a more sophisticated dependency handling than `bastille_list` provides.

**Comment by cedwards** [comment]
I've created a small patch for this. Within the startup script it now reverses the order of the `bastille_list` before stopping the jails. 

Please test this and let me know if it resolves your shutdown ordering issue. If so I'll merge it into the main app.

```diff
diff --git a/usr/local/etc/rc.d/bastille b/usr/local/etc/rc.d/bastille
index 870a285..7d16ba4 100755
--- a/usr/local/etc/rc.d/bastille
+++ b/usr/local/etc/rc.d/bastille
@@ -51,6 +51,8 @@ bastille_stop()

     local _jail

+    ## reverse order of list for shutdown
+    bastille_list=$(echo "${bastille_list}" | awk '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }')
     for _jail in ${bastille_list}; do
         echo "Stopping Bastille Container: ${_jail}"
         ${command} stop ${_jail}
```

**Comment by joh-ku** [comment]
> I've created a small patch for this. Within the startup script it now reverses the order of the `bastille_list` before stopping the jails.
> 
> Please test this and let me know if it resolves your shutdown ordering issue. If so I'll merge it into the main app.
> 
> ```diff
> diff --git a/usr/local/etc/rc.d/bastille b/usr/local/etc/rc.d/bastille
> index 870a285..7d16ba4 100755
> --- a/usr/local/etc/rc.d/bastille
> +++ b/usr/local/etc/rc.d/bastille
> @@ -51,6 +51,8 @@ bastille_stop()
> 
>      local _jail
> 
> +    ## reverse order of list for shutdown
> +    bastille_list=$(echo "${bastille_list}" | awk '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }')
>      for _jail in ${bastille_list}; do
>          echo "Stopping Bastille Container: ${_jail}"
>          ${command} stop ${_jail}
> ```

@cedwards: Successfully tested, thanks!

**Comment by pmather** [comment]
Thank you.  This helps a lot.

**Comment by pmather** [comment]
Actually, I spoke too soon.  The `start` and `stop` methods of the Bastille `rc.d` script work fine with this change, but the `restart` method doesn't.  The reversed `bastille_list` also gets used when doing the `bastille_start` phase of the `restart_cmd`.

**Comment by cedwards** [comment]
I will tinker with this a bit more. Looks like it needs to be set and unset (the missing component here) instead of just changed and left in reverse order.

**Comment by pmather** [comment]
I agree.  In `bastille_stop()` you could save a copy of `bastille_list` to a local variable at the start of the function and then restore `bastille_list` from this copy at the end of the function, before exiting.

**Comment by cedwards** [comment]
Initial testing for this patch works here for start, stop and restart. Please confirm.

dependency should be "DNS server" then "WEB server" (adguard -> pkg-server) in this example.

```diff
diff --git a/usr/local/etc/rc.d/bastille b/usr/local/etc/rc.d/bastille
index 870a285..7d16ba4 100755
--- a/usr/local/etc/rc.d/bastille
+++ b/usr/local/etc/rc.d/bastille
@@ -51,6 +51,8 @@ bastille_stop()

     local _jail

+    ## reverse order of list for shutdown
+    bastille_revlist=$(echo "${bastille_list}" | awk '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }')
+    for _jail in ${bastille_revlist}; do
         echo "Stopping Bastille Container: ${_jail}"
         ${command} stop ${_jail}
```

```
arya ~ # service bastille stop
Stopping Bastille Container: pkg-server
DEBUG: pkg-server adguard
nat cleared
[pkg-server]:
pkg-server: removed

Stopping Bastille Container: adguard
DEBUG: pkg-server adguard
nat cleared
[adguard]:
adguard: removed
```

```
arya ~ # service bastille start
Starting Bastille Container: adguard
[adguard]:
adguard: created

Starting Bastille Container: pkg-server
[pkg-server]:
pkg-server: created
```

```
arya ~ # service bastille restart
Stopping Bastille Container: pkg-server
DEBUG: pkg-server adguard
nat cleared
[pkg-server]:
pkg-server: removed

Stopping Bastille Container: adguard
DEBUG: pkg-server adguard
nat cleared
[adguard]:
adguard: removed

Starting Bastille Container: adguard
[adguard]:
adguard: created

Starting Bastille Container: pkg-server
[pkg-server]:
pkg-server: created
```

**Comment by pmather** [comment]
Thanks, Christer.  I've tested your latest patch and it works correctly for me, too.

**Comment by tucoinfo** [comment]
A useful side effect when you don't want to maintain the list for startup.

`bastille_list="mariadb ALL"`

Shutdown reverse order will take some more thought.
