### ISSUE TITLE
[ENHANCEMENT] Consider explaining sysctl values

### ISSUE THREAD

**Issue by michael-o** [BastilleBSD/bastille#392]
Documentation in https://bastille.readthedocs.io/en/latest/chapters/networking.html says:

```
Lastly, you may want to consider these three sysctl values:

net.link.bridge.pfil_bridge=0
net.link.bridge.pfil_onlyip=0
net.link.bridge.pfil_member=0
```

It doesn't tell why, when and what for I should consider this. Although I read the manpage of `if_bridge(4)` it isn't clear should I use this or not.

**Comment by lifepillar** [comment]
AFAICS, if there is no firewall (in the host or in the jail), or if a firewall is enabled in the host *and* it contains suitable rules to let traffic through the bridge (my current configuration), there is no need to set `net.link.bridge.pfil_bridge` and `net.link.bridge.pfil_member` to `0`.

**Comment by bmac2** [comment]
@cedwards do we want to expand this explanation per the comments???  or has this been expounded on some place in the documentation already?

**Comment by bmac2** [comment]
net.link.bridge.pfil_onlyip  Controls  the  handling  of	non-IP packets
				    which are not passed to [pfil(9)](https://man.freebsd.org/cgi/man.cgi?query=pfil&sektion=9&apropos=0&manpath=FreeBSD+13.2-RELEASE+and+Ports).  Set to 1
				    to only allow IP packets to	pass  (subject
				    to	firewall  rules), set to 0 to uncondi-
				    tionally pass all non-IP Ethernet frames.

       net.link.bridge.pfil_member  Set	to 1 to	enable filtering on the	incom-
				    ing	and outgoing member interfaces,	set to
				    0 to disable it.

       net.link.bridge.pfil_bridge  Set	to 1 to	enable filtering on the	bridge
				    interface, set to 0	to disable it.

**Comment by bmac2** [comment]
Above is the explanation of what these three values do.  Will add this into the documentation and pr it in.

**Comment by bmac2** [comment]
https://github.com/BastilleBSD/bastille/pull/614

PR to submit changes.

**Comment by bmac2** [comment]
PR submitted.
