### ISSUE TITLE
[ENHANCEMENT] Document .hushlogin

### ISSUE THREAD

**Issue by michael-o** [BastilleBSD/bastille#393]
At first use I was surprised not to see a `motd`. Took me some time to find the `.hushlogin` in `bootstrap.sh`.

Please document that this file is created and ist not part of FreeBSD alternatively, disable/remove creation of this file.

**Comment by tobiastom** [comment]
I'd agree to remove `.hushlogin`. if someone really wants it, it could be part of a template.

**Comment by cedwards** [comment]
I will try and document this in the official docs. In the meantime here is some context:

One of the reasons the `.hushlogin` is in place is because the motd will be incorrect on jails older than the host, which has caused user confusion in the past.

The example is creating a 12.2 or 11.4 jail on a 13.0 host system. The motd displayed at login will show `FreeBSD 13.0-RELEASE-p3 (GENERIC) ...` while `freebsd-version` will report 12.2 or 11.4.

**Comment by michael-o** [comment]
If this is the case it is a workaround for a bug which needs to be reported with the FreeBSD base system.

**Comment by bmac2** [comment]
@michael-o did you report this to the FreeBSD base system??  Is there anything that we should code on the bastille side?  This seems to be a non-event for bastille code.  Let me know your thoughts.  

@cedwards  your thoughts also?? is there an actionable item for us here??

**Comment by michael-o** [comment]
> @michael-o did you report this to the FreeBSD base system?? Is there anything that we should code on the bastille side? This seems to be a non-event for bastille code. Let me know your thoughts.
> 
> @cedwards your thoughts also?? is there an actionable item for us here??

No, but looking at "man motd" there is no issue (contrary to https://github.com/BastilleBSD/bastille/issues/393#issuecomment-879565551'):

    DESCRIPTION
         The file /etc/motd is normally displayed by login(1) after a user has
         logged in but before the shell is run.  It is generally used for
         important system-wide announcements.  During system startup, a line
         containing the kernel version string is prepended to this file.

So the kernel version, not world version. All is fine.

Still, settings `.hushlogin` by default isn't right.

**Comment by bmac2** [comment]
@michael-o is this ok to close or is there  an actionable item here?  Per Christer using .hushlogin was on purpose.

**Comment by michael-o** [comment]
> @michael-o is this ok to close or is there an actionable item here? Per Christer using .hushlogin was on purpose.

Until it is not documented,  I am not fine with closing this.

**Comment by bmac2** [comment]
Leaving for Christer to document   @cedwards

**Comment by bmac2** [comment]
PR #619 documents this feature

**Comment by michael-o** [comment]
I have decided to report this anyway with upstream because the output of "uname -v" has very little value and causes issues: https://github.com/BastilleBSD/bastille/issues/393

**Comment by michael-o** [comment]
Same trap: https://github.com/sstallion/dynamic_motd/issues/3

**Comment by michael-o** [comment]
https://reviews.freebsd.org/D43703
