### ISSUE TITLE
OVERLAY order in templating

### ISSUE THREAD

**Issue by eoli3n** [BastilleBSD/bastille#398]
When using a template like [nginx](https://gitlab.com/bastillebsd-templates/nginx), OVERLAY is the last task, then the jail need to be restarted to use the config file.

```bash
$ bastille create nginx 13.0-RELEASE 10.0.0.1

$ bastille bootstrap https://gitlab.com/bastillebsd-templates/nginx

# modify config of nginx.conf and set non existent root

$ bastille template nginx bastillebsd-templates/nginx

$ curl http://10.0.0.1
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

$ bastille restart nginx
[nginx]:
nginx: removed

[nginx]:
nginx: created

$ curl http://10.0.0.1
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.0</center>
</body>
</html>
```

Why using a specific file for ``OVERLAY``, and not an action in ``Bastillefile`` ?
Are ``Bastillefile`` run in declared order ? If not, why not ?

If order needs to be forced, then you should maybe run ``SERVICE`` always after ``OVERLAY``.

**Comment by chriswells0** [comment]
Try using `CP` in your `Bastillefile` instead.

**Comment by eoli3n** [comment]
> Try using CP in your Bastillefile instead.
> The Bastillefile format uses Bastille commands rather than the older template file names.

Thanks, fixed by using:
```
PKG nginx
SYSRC nginx_enable=YES
CMD mkdir -p /data/www
CP usr .
CMD nginx -t
SERVICE nginx restart
FSTAB /data/www data/www nullfs ro 0 0
RDR tcp 80 80
```
The nginx template from gitlab needs to be patched, as it doesn't work as is.

**Comment by chriswells0** [comment]
@cedwards: Just making sure you see this comment about the nginx template since it's probably widely used. I haven't created a GitLab account yet to submit a PR, and I know you're working to refactor that repo anyway.
