### ISSUE TITLE
[BUG] Cannot create a jail with a pure inherited network

### ISSUE THREAD

**Issue by michael-o** [BastilleBSD/bastille#405]
**[MANDATORY] Describe the bug [MANDATORY]**
There is no way to create a jail which should have the following network config:
```
  ip4 = inherit;
  ip6 = disable;
```
Even if you modify `jail.conf` manually `start.sh` will complain about missing `interface` entry.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115
12.2-STABLE
12.2-STABLE
12.2-STABLE

**[MANDATORY] How did you install bastille? (port/pkg/git)**
ports

**[optional] Steps to reproduce?**
Not possible

**[optional] Expected behavior**
Some way not to provide IP address and interface

**[optional]  Additional context**
The purpose is to create a neutral, inactive jail which shall be build and updated based on stacked templates and then used for cloning to create new jails fast. This "template jail" shall contain the following templates: base, base-services, ca-certificates, base-ports. A cloned jail will receive network configuration. host names (`/etc/hosts`), root config + the rest which is usecase specific.

I could create a vnet template jail and clone this, but it would already contain host specific information which does not really make sense here.

**Comment by s1dh** [comment]
I would really need this feature implemented (as iti is in basesystem jail and jail managers alternatives) , this post could be in reference with #369

**Comment by DePingus** [comment]
Does inherit mode work at all? I tried to pass the loopback and then add inherit, but it didn't work.
```
  interface += bastille0;
  ip4.addr += bastille0|192.168.0.10;
  ip4 += inherit;
  ip6 = disable;
```
It hangs on jail start. If I ctrl+c out, the jail has started and I can console in. But when I try to run ntopng inside the jail it hangs without ever throwing errors about inaccessible interfaces.

**Comment by michael-o** [comment]
> Does inherit mode work at all? I tried to pass the loopback and then add inherit, but it didn't work.
> 
> ```
>   interface += bastille0;
>   ip4.addr += bastille0|192.168.0.10;
>   ip4 += inherit;
>   ip6 = disable;
> ```
> 
> It hangs on jail start. If I ctrl+c out, the jail has started and I can console in. But when I try to run ntopng inside the jail it hangs without ever throwing errors about inaccessible interfaces.

This doesn't look inherited, no? You are using the vnet bridge?

**Comment by DePingus** [comment]
I have no idea. Jails are new to me. I was trying to use *both* the loopback (bastille0) and inherit the rest of the adapters with the `+=` operator.

**Comment by michael-o** [comment]
> I have no idea. Jails are new to me. I was trying to use _both_ the loopback (bastille0) and inherit the rest of the adapters with the `+=` operator. The way you worded your bug "pure inherited" made me thing that maybe if I mixed inherited with the basic loopback I wouldn't get the error.

AFAIK, you have to decide: Inherit or VNET

**Comment by DePingus** [comment]
Gotcha. And inherit doesn't work with Bastille. I'm digging into vnet + pf now. Thanks for the help!

**Comment by bmac2** [comment]
the PR is under review and will be merged.  Closing to track with  PR #535

**Comment by michael-o** [comment]
@bmac2, please reopen the PR is still open so is this issue not resolved.
