### ISSUE TITLE
[BUG] Subcommand script are located in the wrong directory

### ISSUE THREAD

**Issue by michael-o** [BastilleBSD/bastille#406]
**[MANDATORY] Describe the bug [MANDATORY]**
For some strange reason all subcommand scripts are located in `/usr/local/share/bastille`, this is incorrect according to `hier(7)`. `share` contains static resources.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115
12.2-STABLE
12.2-STABLE
12.2-STABLE

**[MANDATORY] How did you install bastille? (port/pkg/git)**
ports

**[optional] Expected behavior**
 `hier(7)` expects all subprograms to be in `/usr/local/libexec/bastille`. This is what other applications do.

**[optional]  Additional context**

**Comment by bmac2** [comment]
/usr/local/share/bastille is the designed directory for files to be for bastille.  We have been consistent on this from the beginning. 

Closing:  will not change without a valid technical reason.

**Comment by tobiastom** [comment]
Isn't the `hier(7)` manpage a technical reason. I was wondering about the location for a long time but never had arguments against it.
