### ISSUE TITLE
[BUG] LOG in Bastillefile is not working

### ISSUE THREAD

**Issue by eoli3n** [BastilleBSD/bastille#407]
**[MANDATORY] Describe the bug [MANDATORY]**
I want to be able to log my templatings.
In the ``README.md``, it says that I can log with ``LOG /path/to/file``.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
```bash
root@nas ~# bastille -v && freebsd-version -kru
0.8.20210115
13.0-RELEASE
13.0-RELEASE
13.0-RELEASE
```

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg

**[optional] Steps to reproduce?**
Add this line to a Bastillefile
```
LOG /var/log/bastille/jail1_template.log
```
```bash
$ bastille template jail1 services/jail1
[...]
Failed to execute command: log
```

**[optional] Expected behavior**
Bastille creating a log file on the host (and not the jail) which will be listed with ``bastille list logs``.

**Comment by tobiastom** [comment]
The readme says »Planned template hooks include: `PF`, `LOG`«. Unfortunately they are not implemented yet.

Still, this might be a good issue to track the progress of the `LOG` hook.

**Comment by eoli3n** [comment]
Oh sorry, misunderstood that, ok, let's keep it :)

**Comment by bmac2** [comment]
@tobiastom what readme has this in it??  I cannot find a reference to a LOG hook anywhere.

**Comment by tobiastom** [comment]
It was mentioned [here](https://github.com/BastilleBSD/bastille/commit/da15b4f59a7e15267b25c72053d7bbf86b17a4ab#diff-33b742d364980da0591aa3092d5568835a64b886d24eb4b5dc83416f52e4f892L12), but was it was removed, maybe there is no need for a log hook anymore.

**Comment by bmac2** [comment]
documentation was updated, no action item for this ticket anymore.
