### ISSUE TITLE
[BUG] CMD does not use environment from jail

### ISSUE THREAD

**Issue by michael-o** [BastilleBSD/bastille#410]
**[MANDATORY] Describe the bug [MANDATORY]**
When `CMD` is used in a Bastillefile the environment of the launched command does not correspond to the one in the jail's `login.conf`. This leads to issue when the command relies on a proper environment.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115
12.2-STABLE
12.2-STABLE
12.2-STABLE

**[MANDATORY] How did you install bastille? (port/pkg/git)**
ports

**[optional] Expected behavior**
Currently, it does: `jexec -l <jail> <command>...`. With `jexec -l <jail> -U root <command>...` it would set the user context *after* the jail has been entered in code. See [here](https://github.com/freebsd/freebsd-src/blob/43a58daffe7256f0948ce895fed9fae55dec98fc/usr.sbin/jexec/jexec.c#L105-L137).

**[optional]  Additional context**

I have added the following to my `login.conf`:
```
        :setenv=BLOCKSIZE=K,LSCOLORS=ExGxFxdxCxDxDxhbadExEx,CLICOLOR=YES,LESS=-x4 -RFK,\
HTTP_PROXY=http\c//de.coia.siemens.net\c9400,\
HTTPS_PROXY=http\c//de.coia.siemens.net\c9400,\
FTP_PROXY=http\c//de.coia.siemens.net\c9400,\
NO_PROXY=localhost .siemens.net .siemens.com .siemens.de,\
SSL_CA_CERT_PATH=/etc/ssl/certs,\
EDITOR=vim:\
```

I especially rely the proxy config as well as the `SSL_CA_CERT_PATH` due to a bug in `libfetch`. Without that `CMD pkg` can neither pull from a public repo, e.g., from FreeBSD, not from a repo hosted internally which requires CA certificates installed in the jail with `certctl`. I am not really keen to modify each command to `CMD env VAR=value VAR=value pkg...`

This command either needs to be changed a a new one has to be introduced to make it behave as if one has an interactive session inside the jail.

**Comment by cedwards** [comment]
This has been fixed in merge #418 . Thank you for pointing out the issue and the fix.
