### ISSUE TITLE
[ENHANCEMENT] Color should be easily disabled.

### ISSUE THREAD

**Issue by michaelgalassi** [BastilleBSD/bastille#416]
**Is your feature request related to a problem? Please describe.**
Folk who use dark text on a light background cannot easily read yellow (and other pale) messages.

**Describe the solution you'd like**
A NO_COLOR environment variables has been proposed and many packages already honor this, more information on this is here: https://no-color.org/

**Describe alternatives you've considered**
I tried editing the scripts to initialize the colorizing escape sequences to empty strings but that's quite tedious and needs to be repeated at every release.

**Additional context**

Thank you for your consideration.

**Comment by JRGTH** [comment]
I was thinking this exact same thing time ago, a no color variable in the bastille.conf file should easily address this globally.
lets wait what cedwards thinks about this enhancement.

**Comment by cedwards** [comment]
I support this idea. Happy to merge a PR to support this. Personally can't guarantee how soon I'll have time to write a patch.

**Comment by JRGTH** [comment]
This enhancement has been added in the following PR: 50c09d0

**Comment by hackacad** [comment]
It should be checked via „NO_COLOR“ variable. 

[no-color.org](https://no-color.org/) 
> All command-line software which outputs text with ANSI color added should check for the presence of a NO_COLOR environment variable that, when present (regardless of its value), prevents the addition of ANSI color.

**Comment by JRGTH** [comment]
> It should be disabled via „NO_COLOR“ variable (alternatively or exclusively).
> [no-color.org](https://no-color.org/)
> 
> > All command-line software which outputs text with ANSI color added should check for the presence of a NO_COLOR environment variable that, when present (regardless of its value), prevents the addition of ANSI color.

The suggested PR disables the color withing bastille itself regardless of the term/release used.
However if there is better suggestion cross compatible with FreeBSD lets say from 10.x to 13.x, HBSD,d MidnightBSD etc. I'm happily to test with.

Regards

**Comment by cedwards** [comment]
This fix has been merged and will be available in the next release.
