### ISSUE TITLE
Release mismatch at fstab

### ISSUE THREAD

**Issue by haxo-jvm** [BastilleBSD/bastille#424]
my server is up to date and BastilleBSD is up to date too. I use FreeBSD 13.0-RELEASE and my packages are installed as the Bastille documentation usually indicates. I use thin containers and I have bootstraped 13.0-RELEASE (and upgraded). if I run uname -r on containers it commits 13.0-RELEASE. But the possible problem I found is that the jail setting in jail.conf indicates a mismatch:

in this line
`mount.fstab = /usr/local/bastille/jails/{name}/fstab;`

It leads me to discover that the wrong release is being used, notice this:

`$ cat / usr / local / bastille / jails / haxomatico / fstab
/usr/local/bastille/releases/`_12.1-RELEASE_ `/usr/local/bastille/jails/haxomatico/root/.bastille nullfs ro 0 0`

my logic tells me that line MUST to say this:

`/usr/local/bastille/releases/`**13.0-RELEASE**` /usr/local/bastille/jails/haxomatico/root/.bastille nullfs ro 0 0
`
I have looked for info in the documentation forums etc. and I have not been able to find an answer.

if my Bastille install is misconfigured or has something wrong I would like to be able to correct it. but if this is not the least important I would also like to know so to stop worrying and stop touching Bastille configurations. I don't want to break things but I need it to work as planned.

thanks for the attention to these bits that you wrote.

**Comment by cedwards** [comment]
No issue changing the release manually in the fstab. Make sure the jail is stopped first.

**Comment by haxo-jvm** [comment]
Hello @cedwards
just two questions ..
I wonder if this issue is a bug that you already knew about its existence or is it a new finding. 
The reason for my question is because I want to know if it is scheduled for fix in an upcoming release. 
I understand that there are bugfixes with higher priority and it also depends on human resources, I mean available developers.

 Now my question is whether I should leave this report open to be assigned to someone, or if I should close it because I already got a response. 
I do not want to leave this thread of technical support abandoned and never remember it again, what is the 'netiquette' to follow for situations like this?

thanks

**Comment by cedwards** [comment]
To clarify, `uname -r` will always report host information. I don't recommend using it inside jails. `freebsd-version` is the most reliable report of the jail version status.

**Comment by haxo-jvm** [comment]
thank you, it is important to know how to use Bastille at the right way.

**Comment by bmac2** [comment]
@cedwards  do we need to do anything here?  If not please close.  If yes, tag me in solution writeup.
