### ISSUE TITLE
Long time to start up each jail

### ISSUE THREAD

**Issue by haxo-jvm** [BastilleBSD/bastille#428]
hello,
I would like to know how I can speed up the boot process of my host server where I use Bastille to manage jails.
 the whole boot sequence until reaching the login prompt takes aaaages. 
a large amount of time is consumed at the start of each jail until all of them are turned on and the login prompt appears. 
30 or more seconds to start each jail that contains an 'average sized' webserver, I mean almost small basic sites, with static content, using Nginx server, no MySQL and no PHP. 
I want to know if this is normal and if this slow start behavior is usual. if not I would like to tune it up to correct a possible misconfiguration.

my server is FreeBSD 13.0 (all up to date)
Bastille-0.8.20210115 install from pkg
 nginx-lite Version        : 1.20.1,2
for reproduce this behavior just restart my server and see booting secuence on screen boot each jail tkes too long time.

thanks for your help.

**Comment by cedwards** [comment]
Normal behavior shouldn't take long but I've seen similar reports in the past due to nuance in configuration.

Can you tell me how the network is configured for this jail? bastille0 + pf? VNET?

**Comment by haxo-jvm** [comment]
hello, thank you for your reply.
this is my /etc/pf.conf
$ cat pf.conf
#
#PF FreeBSD firewall
#
vtnet0 = "vtnet0"
lo1="bastille0"
bouncer="192.168.0.250"
proxy="192.168.0.254"
webservers="192.168.0.0/24"
scrub in all fragment reassemble max-mss 1440
icmp_types = "{ echoreq unreach }"
table <jails> persist
nat on $vtnet0 from <jails> to any -> ($vtnet0)
## static rdr example
rdr pass inet proto tcp from any to any port {80, 443} -> 192.168.0.254
pass in quick on $lo1 proto tcp from { $proxy $webservers } to { $proxy $webservers } port 8080 keep state
pass out quick on $lo1 proto tcp from { $proxy $webservers } to { $proxy $webservers } port 8080 keep state

pass in quick on $lo1 proto tcp from { $bouncer $webservers } to { $bouncer $webservers } port 514
pass out quick on $lo1 proto tcp from { $bouncer $webservers } to { $bouncer $webservers } port 514

table <bruteforce> persist
table <webcrawlers> persist
table <rfc6890> { 0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16          \
                  172.16.0.0/12 192.0.0.0/24 192.0.0.0/29 192.0.2.0/24 192.88.99.0/24    \
                  192.168.0.0/16 198.18.0.0/15 198.51.100.0/24 203.0.113.0/24            \
                  240.0.0.0/4 255.255.255.255/32 }
# ---- Unwanted ports and IPs
junk_ports="{ 135,137,138,139,445,68,67,3222 }"
junk_ip="224.0.0.0/4"
# ----
set skip on lo0 
#scrub in all fragment reassemble max-mss 1440
antispoof quick for $vtnet0
block in quick on $vtnet0 from <rfc6890>
block return out quick on egress to <rfc6890>
block all
# ---- Block junk logs
block quick proto { tcp, udp } from any to $junk_ip 
block quick proto { tcp, udp } from any to any port $junk_ports
# ----
# ---- block SMTP out 
block quick proto tcp from $vtnet0 to any port 25
# ----
pass in on $vtnet0 proto tcp to port { 22 } \
    keep state (max-src-conn 15, max-src-conn-rate 3/1, \
        overload <bruteforce> flush global)
pass in on $vtnet0 proto tcp to port { 80 443 } \
    keep state (max-src-conn 45, max-src-conn-rate 9/1, \
        overload <webcrawlers> flush global)
pass out proto { tcp udp } to port { 22 53 80 123 443 }
pass inet proto icmp icmp-type $icmp_types
# ---- END

i hope this help you determine why jails start slow/delayed

i'll stay tuned for your possible recomendations

Thank you

**Comment by bmac2** [comment]
@cedwards is there an actionable item for me here???

**Comment by cedwards** [comment]
Apologies for letting this fall between the cracks.

Looks to me like the `pf.conf` has misconfiguration. The references to the external interface, vtnet0, were referenced as `$vtnet0`. My guess is find/replace error or just simple mistake.

This line in particular could explain the network timeouts due to the misconfiguration:
```
nat on $vtnet0 from <jails> to any -> ($vtnet0)
```

I'm guessing this was the result of `s/ext_if/vtnet0/g` but the `$` remained. Simple mistake.
