### ISSUE TITLE
Explanation about Linux containers

### ISSUE THREAD

**Issue by eoli3n** [BastilleBSD/bastille#437]
Could you explain how Ubuntu containers work ?

- How/Where does Linux kernel run ?
- Why Ubuntu ? Will you support other distros ?

**Comment by AverageHumanoid** [comment]
It uses FreeBSD's Linux binary compatibility layer by loading the `linux`, `linux64`, `linprocfs`, `linsysfs` kernel modules and supports debootstrapping `ubuntu_bionic`, `ubuntu_focal`, `debian_stretch `, `debian_buster`. You can read everything it's doing in https://github.com/BastilleBSD/bastille/blob/master/usr/local/share/bastille/bootstrap.sh#L344.

**Comment by yaazkal** [comment]
Bastille is taking advantage of the FreeBSD Linux Compatibility Layer. That in simple words, allows FreeBSD to run linux binaries, so no linux kernel as far as I understand. You can read more here: https://docs.freebsd.org/en/books/handbook/linuxemu/ 

Ubuntu and some Debian based system can run thanks to [debootstrap](https://www.freebsd.org/cgi/man.cgi?query=debootstrap&apropos=0&sektion=0&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html) but something like CentOS can be run on a jail too (read the first link). I remember someone running OpenSUSE in a jail.

Note that linux jails are experimental at the moment. So is just for fun right now. Not sure what other distros are going to be added. Until now they've been added per own usage by the contributors.

**Comment by eoli3n** [comment]
I didn't try yet, but it's a powerful feature !

**Comment by yaazkal** [comment]
Let us know your results when you play with them

**Comment by bmac2** [comment]
question answered.  Closing.
