### ISSUE TITLE
What is the process for updating thin jail /etc after release upgrade?

### ISSUE THREAD

**Issue by jimbobmcgee** [BastilleBSD/bastille#438]
Hi team;

When provisioning a thin jail, I believe `/etc` is part of the jail-specific filesystem, rather than using the release's shared filesystem.  This makes sense, as config in `/etc` may be specific to a jail.

However, if I am reading the source correctly, when applying `bastille upgrade xx.x-RELEASE yy.y-RELEASE`, nothing then actually attempts to uplift the contents of files in a child jail's `/etc` to the newer release's versions.

Upgrading a *thick* jail seems reasonable -- `bastille upgrade mythickjail yy.y-RELEASE` should be able to update all of the jail filesystem, because it is a full copy of the release, and `freebsd-update` can access and merge all files in the copy.

As such, what is the correct process for bringing a child jail's `/etc` in line with those deployed as part of the newer release?  Some call to `mergemaster` or `etcupdate`?  Some other diff tool between the child's `/etc` and the release's `/etc`?  

I briefly looked at the man pages for `mergemaster` and `etcupdate` and couldn't see a viable way to supply the *old* release version for a three-way merge (which is what `freebsd-update` does, calling `diff3 oldversion newversion existingfile`).  Perhaps I am way off base...?

If there is a reasonable process we can take, is it worth creating a subcommand specifically for updating and merging a thin child jail's `/etc`?  Something along the lines of `bastille etcupdate mythinjail --from xx.x-RELEASE`?

**Comment by bmac2** [comment]
@cedwards  you took this one 2 years ago.  Is there a solution already installed for this??

**Comment by bmac2** [comment]
The upgrade process has been added to the documentation.  Closing as completed.

**Comment by jimbobmcgee** [comment]
Can you indicate where in the documentation you cover merging in the `/etc` folder of a specific jail, after upgrading the release that the jail uses?
