### ISSUE TITLE
[ENHANCEMENT] Update /etc/ssl/certs and /etc/ssl/blacklisted

### ISSUE THREAD

**Issue by manufactory** [BastilleBSD/bastille#441]
**Is your feature request related to a problem? Please describe.**
`freebsd-update` updates `/etc/ssl/certs` and `/etc/ssl/blacklisted`. bastille does not take those updates into account. I'm well aware that each jail has its own copy of `/etc/` by design, however had I not diffed `/etc/` by hand, I wouldn't have noticed the outdated certificate files. Obviously, you don't want jails that trust blacklisted certificates. 

**Describe the solution you'd like**
Automatically copy `/etc/ssl/certs` and `/etc/ssl/blacklisted` from `$bastille_releasesdir/$RELEASE/`

**Describe alternatives you've considered**
Maybe just hint the user, that `freebsd-update` updated files in `/etc/`.

**Additional context**

**Comment by michael-o** [comment]
Does freebsd-update really runs certctl?

**Comment by cedwards** [comment]
Thank you for submitting this enhancement. Apologies for the time between submission and now...

Looks like `freebsd-update` does in fact run `certctl` during the process. See here for the commit history (https://git.des.dev/FreeBSD/src/commit/2b17527cea45248852c52713bf6515c776730342?style=split)

The integration with `freebsd-update` solves many of the cases where this enhancement would need to be implemented, which is great. Updating a "thick" jail, for example, will automatically update trusted and untrusted certs during the update. No additional steps are required. New jails will also get the updated information at creation. The only remaining case where this is unhandled is updates to an existing "thin" jail.

After some experimentation I think the simplest solution right now is to include one additional step in the documented update process. Simply execute `bastille cmd ALL certctl rehash` and the  links in `/etc/ssl/{certs,blacklisted}` will be updated with the latest values on all jails.

I will create a task to update the documentation and communicate the recommended step.
