### ISSUE TITLE
Is there any way to assign a MAC address to a VNET/DHCP on creation?

### ISSUE THREAD

**Issue by Bern586** [BastilleBSD/bastille#449]
I couldn't find any documentation about it, just the example
`bastille create -V nginx 12.2-RELEASE 0.0.0.0 re0`

Can bastille manage MAC addresses right now?

Thanks in advance

**Comment by michael-o** [comment]
No, it is autoderived from the NIC the bridge is attached.

**Comment by Bern586** [comment]
Thank you Michael,
If not on creation, is there any workaround I could use to accomplish this?

**Comment by michael-o** [comment]
This is what Bastille does:
https://github.com/BastilleBSD/bastille/blob/c02a8735d8adcb57f8c0241c013ebfdd56f750a1/usr/local/share/bastille/create.sh#L213-L215

So, here is the jib script does the actual magic:
https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/share/examples/jails/jib#L318-L330

One would need to change the jib script to passthrough a MAC address or not use the jib script in bastille and do the magic manually.

**Comment by cedwards** [comment]
This is not supported during create but you can manually fix a mac address like this:

```
vnet;
vnet.interface = e0b_bastille1;
exec.prestart += "jib addm bastille1 em0";
exec.prestart += "ifconfig e0a_bastille1 ether 02:20:99:1f:8c:18";
exec.poststop += "jib destroy bastille1";
```

I've used this in my home lab by manually adding the second prestart line.

**Comment by michael-o** [comment]
> This is not supported during create but you can manually fix a mac address like this:
> 
> ```
> vnet;
> vnet.interface = e0b_bastille1;
> exec.prestart += "jib addm bastille1 em0";
> exec.prestart += "ifconfig e0a_bastille1 ether 02:20:99:1f:8c:18";
> exec.poststop += "jib destroy bastille1";
> ```
> 
> I've used this in my home lab by manually adding the second prestart line.

How can this be? `e0a_bastille1` is connected to the bridge, not the jail. You have modified the wrong pair end. It should be `e0b_bastille1`, no?
