### ISSUE TITLE
[BUG] bastille is using jls from PATH, therefore could use wrong executable

### ISSUE THREAD

**Issue by arthepsy** [BastilleBSD/bastille#460]
**[MANDATORY] Describe the bug [MANDATORY]**
`bastille` is using `jls` from `PATH` environment variable and if it contains `/usr/local/bin` before `/usr/sbin`, then `/usr/local/bin/jls` (from `sleuthkit`) could be used, therefore, most of `bastille` is in non-working state. For example, this can happen using `doas` and having `sleuthkit` installed.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.9.20210714
13.0-RELEASE-p4
13.0-RELEASE-p4
13.0-RELEASE-p5

**[MANDATORY] How did you install bastille? (port/pkg/git)**
port

**[optional] Steps to reproduce?**
```
% doas bastille list
jls: illegal option -- N
Invalid argument: (null)
usage: jls [-f fstype] [-i imgtype] [-b dev_sector_size] [-o imgoffset] [-vV] image [inode]
        -i imgtype: The format of the image file (use '-i list' for supported types)
        -b dev_sector_size: The size (in bytes) of the device sectors
        -f fstype: File system type (use '-f list' for supported types)
        -o imgoffset: The offset of the file system in the image (in sectors)
        -v: verbose output to stderr
        -V: print version
```
```
% doas which jls
/usr/local/bin/jls
% doas pkg which /usr/local/bin/jls
/usr/local/bin/jls was installed by package sleuthkit-4.7.0
% doas sh -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**[optional] Expected behavior**
I would expect `bastille` to work independent of `PATH` environment variable.
This could be accomplished by using absolute path to `jls`, i.e., `/usr/sbin/jls`.

**Comment by cedwards** [comment]
I have created a patch for this issue.

Expected to be included in the upcoming Christmas release.
