### ISSUE TITLE
what/where are bastille backups ?

### ISSUE THREAD

**Issue by eoli3n** [BastilleBSD/bastille#468]
I just found a ``backups`` dataset created by bastille.
```bash
root@nas ~# zfs list | grep bastille/backups
zroot/bastille/backups                  96K   215G       96K  /usr/local/bastille/backups
```

In the README.md
> list        List containers, releases, templates, logs, limits or backups.

What are those bastille backups, how to create them ?

**Comment by cedwards** [comment]
Bastille will store exported jails in the backups directory.

`bastille export TARGET` will create a dated export of the jail. This can be later imported from another host or used as a snapshot on the same host.

**Comment by eoli3n** [comment]
Thanks :)
