### ISSUE TITLE
bastille create 12.1-RELEASE fails

### ISSUE THREAD

**Issue by cedwards** [BastilleBSD/bastille#49]
Missed a test; easy fix.

Update `/usr/local/share/bastille/create.sh`:

```patch
--- create.sh
+++ create.sh
@@ -211,6 +211,9 @@
 12.0-RELEASE|12.0-release)
     RELEASE="12.0-RELEASE"
     ;;
+12.1-RELEASE|12.1-release)
+    RELEASE="12.0-RELEASE"
+    ;;
 11-stable-LAST|11-STABLE-last|11-stable-last|11-STABLE-LAST)
     RELEASE="11-stable-LAST"
     ;;
```
This fix and an upgrade to the entire bootstrap/create release verification pending 0.5.x release.

**Comment by jpmens** [comment]
Your patch sets `RELEASE=12.0-RELEASE` for 12.1. Is that really meant that way?

**Comment by JRGTH** [comment]
> Your patch sets `RELEASE=12.0-RELEASE` for 12.1. Is that really meant that way?

Hi jpmens, the release name handling was [changed](https://github.com/BastilleBSD/bastille/commit/9bc8837f77a689a3cde26188637c187f766c14e0#diff-9ed5be34a34144aee2cbd528d0787bbe) recently.

**Comment by jpmens** [comment]
OK, thank you. (I commented here as this issue was still open.)
I’ll wait for the next Bastille release.

**Comment by cedwards** [comment]
The fix for this has been merged. It will appear in the next release (planned 0.5.20191125). Closing this as fixed.
