### ISSUE TITLE
[BUG] ssh-keygen within a Bastille container disconnects ssh server connection

### ISSUE THREAD

**Issue by bedwardly-down** [BastilleBSD/bastille#492]
**[MANDATORY] Describe the bug [MANDATORY]**
Generating a pair of ssh keys disconnects ssh connection from server.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
bastille: 0.9.20211225
freebsd: 13.0-RELEASE-p6

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg

**[optional] Steps to reproduce?**
1) SSH into a remote Freebsd server
2) Create a test jail if there are none using bastille
3) Shell into that jail using `bastille console <target>`
4) `ssh-keygen`
5) Follow the prompts until you get to Enter Passphrase
6) Use a password generator (like the one in your password manager) to create a new one
7) Copy and paste it into the passphrase prompt

**[optional] Expected behavior**
To be able to generate an ssh key pair that is only for that jail

**[optional]  Additional context**
I was using the Windows Terminal and WSL2 to ssh into my server. My WSL2 OS is Gentoo with some heavyish modifications, but I don't see that being super relevant here.

**Comment by ddowse** [comment]
Can't confirm, please use a different terminal emulator ( e.g PuTTY ) and retry. The only distant idea that I have is that on your machine pasting the text sends some control characters to the wrong application.

**Comment by bmac2** [comment]
@bedwardly-down is this still an issue or did this get solved??? Ticket is 1.5 years old and no other report.  please advise.

**Comment by bmac2** [comment]
@bedwardly-down  closing this ticket.  IF this is still an issue and can be reproduced reach out to me and we will reopen the ticket and investigate more.
