### ISSUE TITLE
[ENHANCEMENT] Tear down network after stopping container.

### ISSUE THREAD

**Issue by eborisch** [BastilleBSD/bastille#499]
Services that need to synchronize state with some external (network) system during shutdown are unable to do that currently from within a Bastille jail; during the `stop` action, the network is yanked before the container is stopped.

There are four commented steps in `stop`:

1. remove ip4.addr from firewall table:jails :  _stops new outbound connections_
2. Check if pfctl is present : _stops new inbound (rdr) connections_
3. remove rctl limits
4. stop container

I would suggest re-ordering these to (at least):

1. Check if pfctl is present (remove rdr rules) : _stops new inbound (rdr) connections_
2. remove rctl limits
3. stop container
4. remove ip4.addr from firewall table:jails :  _stops new outbound connections_

and potentially:

1. remove rctl limits
2. stop container
3. Check if pfctl is present (remove rdr rules) : _stops new inbound (rdr) connections_
4. remove ip4.addr from firewall table:jails :  _stops new outbound connections_

This would allow jailed services to access the network during the `stop` process. Explicitly, I'm using Zabbix, which wants to sync history on shutdown, but it ends up timing out while trying to connect to the database which is hosted on a separate system.

**Comment by zilti** [comment]
Since the fix for this got merged, it'd be good to close this issue.
