### ISSUE TITLE
[BUG] hardcoded pf paremeters

### ISSUE THREAD

**Issue by njthomas** [BastilleBSD/bastille#508]
**Describe the bug**
Bastille hardcodes the name of pf external interface as `$ext_if`. This is fine for users creating new pf rules. But for those with existing rules, this will break things.

**Bastille and FreeBSD version**
0.9.20211225, 13.0-RELEASE-p7, 13.0-RELEASE-p3, 13.0-RELEASE-p7

**How did you install bastille? (port/pkg/git)**
pkg

**Steps to reproduce?**
I use the following in `/etc/pf.conf`:
```
table <jails> persist
nat on $EXT_NIC from <jails> to any -> ($EXT_NIC:0)
rdr-anchor "rdr/*"
```

(I am using `$EXT_NIC` above because I have existing pf policy that already uses this convention.)

Abbreviated out from from create subcommand below:

```
$ sudo bastille create foobar 13.0-RELEASE 10.1.1.1
[...]

Template applied: default/base

Template applied: default/thin

ext_if not defined in pf.conf
[...]
```

**Expected behavior**
The external interface name should be configurable in `bastille.conf` (probably the pf table name `<jails>` as well).

**Comment by Freaky** [comment]
FreeBSD should really follow OpenBSD's lead and put default-route interfaces in the "egress" group, negating the need to hardcode external interface names.
