### ISSUE TITLE
[ENHANCEMENT] bootstrap Alpine Linux and create Alpine Linux container

### ISSUE THREAD

**Issue by jemail99** [BastilleBSD/bastille#512]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The ability to bootstrap and then create an Alpine Linux Container.

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.alpinelinux.org/
Alpine Linux is a security-oriented, lightweight Linux distribution based on musl libc and busybox.
I use Alpine Linux as containers on linux and they are small (5.3 MB rootfs container), simple (no systemd) and very easy to use (good package selection, aarch64 available, I boot a RPi4 8GB with freeBSD 13.0 aarch64).
Being able to create Alpine Linux containers using bastille would be an excellent addition to bastille functionality.

**Comment by yaazkal** [comment]
Thanks. To understand your scenario: what is the app that runs on Alpine but not on FreeBSD?

**Comment by zilti** [comment]
You could proxy it through Caddy or Nginx.

**Comment by bmac2** [comment]
proxy thru an nginx setup is a valid solution.   Various linux setups are being used/worked on, not sure about alpine.  A pr to support Alpine would be welcomed.  Closing as won't do now.

**Comment by bmac2** [comment]
ALSO Alpine has been run in a freebsd jail.  If you need help on how to do it ask in the discord channel.
