### ISSUE TITLE
[HELP] nullfs mount only lists one level of folders

### ISSUE THREAD

**Issue by jemail99** [BastilleBSD/bastille#517]
Hi,
```
bastille -v
0.9.20220216
```
I am trying to mount a zpool (storage mounted on /storage in host) in a jail (freebsd-file-server on /storage in jail)
freebsd-file-server fstab contains:
`/storage /usr/local/bastille/jails/freebsd-file-server/root/storage/ nullfs rw 0 0`

freebsd-file-server jail.conf contains:
```
freebsd-file-server {
  devfs_ruleset = 4;
  enforce_statfs = 0;
  exec.clean;
  exec.consolelog = /var/log/bastille/freebsd-file-server_console.log;
  exec.start = '/bin/sh /etc/rc';
  exec.stop = '/bin/sh /etc/rc.shutdown';
  host.hostname = freebsd-file-server;
  mount.devfs;
  mount.fstab = /usr/local/bastille/jails/freebsd-file-server/fstab;  
  path = /usr/local/bastille/jails/freebsd-file-server/root;
  securelevel = 2;

  interface = genet0;
  ip4.addr = 192.168.1.101;
  ip6 = disable;
}
```
On the host
```
zpool list storage
NAME      SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
storage   880G  2.47G   878G        -         -     0%     0%  1.00x    ONLINE  -

zfs list
NAME                                                            USED  AVAIL     REFER  MOUNTPOINT
storage                                                        2.47G   850G      128K  /storage
```
Doing ls -al in the jail of /storage only lists directories to a depth of 1 below /storage and directory contents are not listed.
If I create a file on the jail in /storage it does not appear in the host /storage directory and vice versa, creating anything on the host does not show up in the jail.
I have done this in iocage with no problems where ls-al in the jail produces the expected contents of /storage.
What am i doing wrong?
Any help would be appreciated.

**Comment by jschmidt3786** [comment]
try creating a dataset under the pool 'storage' and nullfs mount that.

**Comment by jemail99** [comment]
Thank you for your reply.

The zpool storage already has several existing datasets under it. A ls -al will list these datasets but they are empty and their contents are not shown.
I can create a folder on the guest for each of these datasets and nullfs mount those.
However, this is tedious, particularly if I create more and more datasets on the storage zpool as I would have to recreate a folder structure that matches the dataset structure then nullfs mount each dataset individually to its corresponding guest folder.

Is this a limitation of zfs and jails? That it is not possible to mount the zpool in a jail and have all it contents, datasets and/or folders, accessible inside the jail?

**Comment by soupbowl** [comment]
I had this issue years ago before bastille, I solved it by mounting everything separately with nullfs. I assume there is a freebsd setting somewhere that allows you to mount with a deeper depth, but I gave up and just make the extra mount points.

**Comment by bmac2** [comment]
per comments this is not a bastille issue, but a freebsd dataset issue.
