### ISSUE TITLE
Unable to fetch MANIFEST. See 'bootstrap urls'.

### ISSUE THREAD

**Issue by justinnoor** [BastilleBSD/bastille#518]
**Error: Unable to fetch MANIFEST. See 'bootstrap urls'.**

The following error occurs while attempting to bootstrap 12.2-RELEASE:
`# bastille bootstrap 12.2-RELEASE update`
`Unable to fetch MANIFEST. See 'bootstrap urls'.`

Current bootstrap url:
`bastille_url_freebsd="http://ftp.freebsd.org/pub/FreeBSD/releases/"`

**Bastille and FreeBSD version**
``# bastille -v 0.9.20220216``
``# freebsd-version -kru 
12.2-RELEASE-p14
12.2-RELEASE-p14
12.2-RELEASE-p15
You have new mail.
``

**Installation**
``# pkg install bastille``

**PF ruleset**
ext_if="vtnet0"

set block-policy return
scrub in on $ext_if all fragment reassemble
set skip on lo0

table \<jails> persist
nat on $ext_if from <jails> to any -> ($ext_if:0)
rdr-anchor "rdr/*"

block in all
pass out quick keep state
antispoof for $ext_if inet
pass in inet proto tcp from any to any port { 22 } flags S/SA keep state

**Additional context**
FreeBSD installation performed on a Digital Ocean droplet.

**Comment by cedwards** [comment]
Bastille pulls the bootstrap files from the upstream FreeBSD mirrors.

The problem is that 12.2, now end of life, has been removed from upstream.

My recommendation is use 12.3, which I've confirmed is available upstream.

**Comment by justinnoor** [comment]
> Bastille pulls the bootstrap files from the upstream FreeBSD mirrors.
> 
> The problem is that 12.2, now end of life, has been removed from upstream.
> 
> My recommendation is use 12.3, which I've confirmed is available upstream.

Understood. Interestingly Digital Ocean droplets currently ship with 12.2. Is it an issue if the host version is less than the container version?

**Comment by cedwards** [comment]
Container version should be less than or equal to host version. I can't make any guarantees if you run 12.3 container on 12.2 host. Upgrade the host in-place first if you need to stay in place.

Tip: I recently saw some news about DigitalOcean dropping FreeBSD completely. I can recommend Vultr as an alternative that supports FreeBSD well and provides 13.x images.

**Comment by justinnoor** [comment]
> Container version should be less than or equal to host version. I can't make any guarantees if you run 12.3 container on 12.2 host. Upgrade the host in-place first if you need to stay in place.
> 
> Tip: I recently saw some news about DigitalOcean dropping FreeBSD completely. I can recommend Vultr as an alternative that supports FreeBSD well and provides 13.x images.

Yes we will use Vultr instead. Just submitted a ticket to DO asking them about that.

**Comment by justinnoor** [comment]
DO response:

Hello there,

Thanks for reaching out to us.

We understand that FreeBSD 12.2 release went EOL on 31 March, 2022. We have internal projects regarding this, and the action plan is to retire FreeBSD versions through the UI starting June 2022 and through the API starting August 2022.

We get that this might not be great news for customers like you who want to use FreeBSD on our platform, and you can still do that using Custom images, or through a Snapshot of your FreeBSD based Droplet. Learn more about custom images here:

https://docs.digitalocean.com/products/images/custom-images/

Please note that this retiring process will not impact current Droplets. I hope this helps and please do let us know if you have any further questions.

Kindly,

Amxxxx
Cloud Support Engineer
ref:_00Df218t5m._5004P1ukE1s:ref_
