### ISSUE TITLE
[ENHANCEMENT] [Solution] csh  autocompletion for bastille

### ISSUE THREAD

**Issue by jemail99** [BastilleBSD/bastille#524]
**Is your feature request related to a problem? Please describe.**
N\A

**Describe the solution you'd like**
Auto completion for csh and bash shells for bastille commands, especially on jail names.

**Describe alternatives you've considered**
N\A

**Additional context**
N\A

**Comment by jemail99** [comment]
I've cobbled together a basic csh completion for bastille. It is based on one I found for ezjail-admin.
The file will complete on the bastille command as follows:

`bastille <cmd> <jail-name>`

eg. bastille htop my-jail using tab or whatever your shell completion keys is to provide completion.

It will also provide the --help command as an option to complete after providing a current list of commands.
`bastille <cmd> --help`

```
  # alias _bjails 'jls -d name'
  # jls -d only lists active or dying jails
  # but it is better to list all defined jails
  alias __bjails 'ls /usr/local/bastille/jails'
  alias __btemplates 'find /usr/local/bastille/templates -type d -mindepth 1 -maxdepth 2 -name "*" | cut -b 31-'

  complete bastille	'p/1/(clone cmd console convert cp destroy \
  			export htop import list limits pkg restart rdr \
			service start stop sysrc template top \
  			update upgrade verify zfs)/' \
  			'n/clone/`__bjails | xargs echo --help`/' \
  			'n/cmd/`__bjails | xargs echo --help`/' \
  			'n/console/`__bjails | xargs echo --help`/' \
  			'n/convert/`__bjails | xargs echo --help`/' \
  			'n/cp/`__bjails | xargs echo --help`/' \
  			'n/create/`__bjails | xargs echo --help`/' \
  			'n/destroy/`__bjails | xargs echo --help`/' \
  			'n/export/`__bjails | xargs echo --help`/' \
  			'n/htop/`__bjails | xargs echo --help`/' \
  			'n/import/`__bjails | xargs echo --help`/' \
  			'n/list/`__bjails | xargs echo --help`/' \
  			'n/limits/`__bjails | xargs echo --help`/' \
  			'n/pkg/`__bjails | xargs echo --help`/' \
  			'n/restart/`__bjails | xargs echo --help`/' \
  			'n/rdr/`__bjails | xargs echo --help`/' \
  			'n/service/`__bjails | xargs echo --help`/' \
  			'n/start/`__bjails | xargs echo --help`/' \
  			'n/stop/`__bjails | xargs echo --help`/' \
  			'n/sysrc/`__bjails | xargs echo --help`/' \
			'n/template/`__bjails | xargs echo --help`/' \
			'n/top/`__bjails | xargs echo --help`/' \
  			'n/update/`__bjails | xargs echo --help`/' \
  			'n/upgrade/`__bjails | xargs echo --help`/' \
  			'n/verify/`__btemplates`/' \
  			'n/zfs/`__bjails | xargs echo --help`/' \
			'p/3/`__btemplates`/'
```

My csh-fu is not so good so if anyone can help with figuring out how to complete the following commands  more fully that would be appreciated.
The following commands need more work to handle options:
  Usage: bastille bootstrap [release|template] [update|arch]
  Usage: bastille cp [OPTION] TARGET HOST_PATH CONTAINER_PATH
  Usage: bastille export | option(s) | TARGET | PATH
  Usage: bastille import [option(s)] FILE
  Usage: bastille list [-j|-a] [release [-p]|template|(jail|container)|log|limit|(import|export|backup)]
  Usage: bastille pkg [-H|--host] TARGET command [args]
  Usage: bastille template TARGET|--convert project/template
  Usage: bastille verify [release|template]

Please use this as needed. Perhaps it could be tested and added to a release.

**Comment by cqexbesd** [comment]
If I understand your question regarding `verify` et al then maybe one of these is what you are after. The first will add a `/` to the end of the release names if some tcsh setting is on which is a bit annoying, but the second one is hideous.

```
n@verify@D:/usr/local/bastille/releases/@
```
or
```
'n@verify@`find /usr/local/bastille/releases -mindepth 1 -maxdepth 1 -type d  -exec basename \{\} \;`@'
```

Perhaps form that you can extrapolate to the other commands.

**Comment by bmac2** [comment]
@jemail99   is there a request or code we need to include IN bastille?  This seems a request for code for your shell.  IF I am wrong let me know and explain the ask so I understand what we need to do.
