### ISSUE TITLE
syntax error in jail.conf

### ISSUE THREAD

**Issue by jpmens** [BastilleBSD/bastille#53]
```
$ bastille -v
0.4.20190714

$ bastille create b1 12.0-RELEASE 10.1.0.1
$ bastille start b1
[b1]:
jail: /usr/local/bastille/jails/b1/jail.conf line 1: ;: syntax error

$ head -1 /usr/local/bastille/jails/b1/jail.conf
interface = ;
```

Changing that line to

```
interface = lo1;
```

solves the issue.

**Comment by JRGTH** [comment]
> 
> Changing that line to
> 
> ```
> interface = lo1;
> ```
> 
> solves the issue.

Hi, this commonly happens by incomplete network configuration in either the host and/or the bastille.conf file if missing parameters.

A simple solution for basic/shared IP jails, as of later bastille updates it added the ability to specify any system available network interface during jail creation, by explicitly specifying it after the IP address e.g:

`Usage: bastille create name release ip | interface.`

where "interface" can be either an lo1, em0 etc., if the network interface pass validation , the created jail will use this NIC for simple/shared IP based jails unless vnet configured, but be aware that bastille does not care is this external NIC is active or not.

Second option, under bastille.conf file, setting an external NIC e.g:  bastille_jail_external="em0" will tell bastille to always use this NIC when creating jails unless override by the first option above.

Third option is for a more complex/specific network scenarios such vnet, ipv6, firewall etc., it requires for more advanced manual work by the user in the host, the jail/jail.conf etc.

Regards

**Comment by jpmens** [comment]
@JRGTH thank you. I selected the `bastille_jail_external` method which works for me.

Your very good explanation could be copy/pasted into the README, IMO. :)

**Comment by JRGTH** [comment]
> @JRGTH thank you. I selected the `bastille_jail_external` method which works for me.
> 
> Your very good explanation could be copy/pasted into the README, IMO. :)

Hi, thanks for confirming that the second option did worked for you.

Currently the Bastille community is working on some features and improvements for the framework, but hopefully the documentation will get some updates as well.

Regards

**Comment by cedwards** [comment]
The fix for this has been merged. It will appear in the next release (planned 0.5.20191125). Closing this as fixed.

Thank you for taking the time to submit the issue.
