### ISSUE TITLE
bastille ought to check for missing template

### ISSUE THREAD

**Issue by jpmens** [BastilleBSD/bastille#54]
```
$ bastille -v
0.4.20190714

$ bastille template b1 j0
[b1]:
Template Complete.
```

The template `j0` doesn't exist; it would be nice if bastille either complained (ENOENT) or was silent to indicate non-existence. :)

**Comment by cedwards** [comment]
The fix for this has been merged. It will appear in the next release (planned 0.5.20191125). Closing this as fixed.

Thank you for taking the time to submit the issue.
