### ISSUE TITLE
Where is the jail.conf file?

### ISSUE THREAD

**Issue by justinnoor** [BastilleBSD/bastille#540]
**Where is the jail.conf file?**

The Bastille documentation states that ["A jail.conf template is used each time a new container is created."](https://bastille.readthedocs.io/en/latest/chapters/jail-config.html), but the file is not created after launching a new container on the host. Do we need to manually create jail.conf?

**FreeBSD and Bastille version**
`bastille -v && freebsd-version -kru`
`0.9.20220216`
`13.0-RELEASE-p12`
`13.0-RELEASE-p12`
`13.0-RELEASE-p12`

**How did you install bastille?**
 `freebsd-update fetch install`
  `reboot`
  `freebsd-version`
  `pkg bootstrap`
  `pkg update`
  `pkg upgrade`
  `pkg install bastille sudo vim`

  `sysrc pf_enable="yes"`
  `sysrc pflog_enable="yes"`
  `sysrc bastille_enable="yes"`

  `bastille_zfs_enable="yes"`
  `bastille_zfs_zpool="zroot"`

  `sysrc cloned_interfaces+=lo1`
  `sysrc ifconfig_lo1_name="bastille0"`
  `service netif cloneup`

  `bastille bootstrap 13.0-RELEASE update`

  `bastille create lb_0 13.0-RELEASE 192.168.50.10`
  `bastille pkg lb_0 install -y nginx postgresql14-server redis`

**Comment by JRGTH** [comment]
Bastille will create the **jail.conf** upon creation and it is located under the corresponding jail directory, same applies for the **fstab** and related config filles when required.

**Example locations for Bastille jail config files:**
`/usr/local/bastille/jails/{jail_name}/jail.conf`
`/usr/local/bastille/jails/{jail_name}/fstab`

Regards

**Comment by justinnoor** [comment]
Thank you.
