### ISSUE TITLE
[BUG] Honor $EDITOR

### ISSUE THREAD

**Issue by arrowd** [BastilleBSD/bastille#542]
`bastille edit` doesn't honor $EDITOR and always uses `vi` to open files.

**Comment by JRGTH** [comment]
Hello, both `setenv` and `export` is working fine here.
```
# bastille -v
0.9.20220216
```

`setenv EDITOR editorcmd` , or `export EDITOR=editorcmd`


Between for `csh` I've added the `ee` editor permanently in the `.cshrc` file with:
`setenv EDITOR ee`

And for `sh` in the `.profile` with:
```
EDITOR=ee
export EDITOR
```

Regards

**Comment by arrowd** [comment]
Yeah, sorry for the noise, the problem was `sudo` not preserving env.
