### ISSUE TITLE
[BUG]  IPV6 Addresses are only partially recognized

### ISSUE THREAD

**Issue by PythonLinks** [BastilleBSD/bastille#547]
**[MANDATORY] Describe the bug [MANDATORY]**

Create works well with ipv4 addresses but not with ipv6 addresses

`
 bastille create alcatraz 13.1-RELEASE 2001:19f0:5c00:1f06:0000:0000:0000:0000  vtnet0
bastille create beta 13.1-RELEASE 192.168.0.0  vtnet0

 bastille list
 JID             IP Address      Hostname                      Path
 alcatraz         &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;                    alcatraz                      /usr/local/bastille/jails/alcatraz/root
 beta            192.168.0.0     beta                          /usr/local/bastille/jails/beta/root

`
Even though I have already configured the ipV6 address. 

ifconfig_vtnet0_alias0="inet6 2001:19f0:5c00:1f06:0000:0000:0000:0000 prefixlen 64

In fact I can ping the ipv6 container alcatraz from root.  I can do a wget from within the ipv6 alcatraz container, so networking does work, but just bastille does not seem to know about it.  It keeps 
telling me missing ip address. 

 bastille stop alcatraz

Jail IP not found: alcatraz

I am running on vultr which gives me both an ipv4 address, and a ton of ipv6 addresses. 

**[MANDATORY] Bastille and FreeBSD version 
`
bastille -v && freebsd-version -kru
0.9.20220216
13.1-RELEASE-p2
13.1-RELEASE-p2
13.1-RELEASE-p2

`

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg 
 

**[optional] Expected behavior**
I would like bastille to know about the ipv6 address, then I can do rdr, and get nginx to work.

**Comment by PythonLinks** [comment]
I am also not able to do a git clone inside of the contianer.  I can do wget of git files, but not git clones of repositories.  Is this a separate bug, or is it related to this problem?  I do not know.

**Comment by soupbowl** [comment]
If your jail is ipv6 only or prefers ipv6, assuming your git clone is from github, it does not support ipv6 I believe. I can't really help you with your main issue, I use ipv6 with VNET and SLAAC. To get things working that way the container requires a couple rc.conf flags. 

if you ping google does it default to an ipv6 address? if not what if you ping -6 google.com is it able to ping via ipv6?

**Comment by jpds** [comment]
The IPv6 address is displayed if you run `bastille list --all`.

**Comment by bmac2** [comment]
with the October 2023 release IPv4/6 dual stack is now supported.  If there are still items not working as planned please submit a new ticket with details of exactly what is failing for ipv6.    @PythonLinks
