### ISSUE TITLE
[ENHANCEMENT] FIX DOCUMENATION INCONSISTENCiES

### ISSUE THREAD

**Issue by PythonLinks** [BastilleBSD/bastille#548]
**Is your feature request related to a problem? Please describe.**
Well there are 3 inconsitent versions of the documentation.  On the github read me, on the documentation pages and on the getting started pages.   I missed the getting started pages, did not do the pf configuration correctly, and it took me forever to figure out my mistakes.  ALso I am using 13.1-RELEASE, but also not clear what the releases are. 
Maybe there are two sets of releases, one for templates and one for the software.  Not clear what the most recent version of the template releases are. 
The docs should just link to the list of template releases, lest they fall behind.   

**Describe the solution you'd like**

Just a single version of the documentation, with clear links. 

**Describe alternatives you've considered**

I have become an expert at reading all 3 versions of the docs. 

**Additional context**

I am still so impressed by this.

**Comment by PythonLinks** [comment]
So I am becoming an expert on the differences between the documenation versions.  the big one is that the /etc/pf.conf files are different.  I am assuming that github is more recent. 

The next problem in the getting started documentation is 
bastille bootstrap 13.1-RELEASE update

It does not work.  it cannot find the manifest file. 
> Unable to fetch MANIFEST. See 'bootstrap urls'.

It needs to be split into two lines. 
> bastille bootstrap 13.1-RELEASE 

> bastille bootstrap 13.1-RELEASE update

And with those changes, I now get basic conainers (no vnet) working
HURRAH

**Comment by bmac2** [comment]
As of the latest release all the files are now in sync.   FOR REFERENCE, the github files are the most updated over the released versions.
