### ISSUE TITLE
[QUESTION] How to template changes to jail.conf

### ISSUE THREAD

**Issue by scruffydan** [BastilleBSD/bastille#555]
I recently was upgrading my Samba Jail to Samba 4.16 (from 4.13) and I ran into a bunch of issues. During the troubleshooting I discovered that I needed to make the following changes to the `jail.conf` 

Change `enforce_statfs = 2;` to `enforce_statfs = 1;`

 Add the following lines:
```
allow.mount;
allow.mount.fdescfs;
```

My question is how to add these changes to the `Bastillefile` template so they are automatically applied when the Jail is created.

Thanks

**Comment by cedwards** [comment]
You can automate changes to the `jail.conf` using the bastille `config` option (available in cli and templates).

CLI:
```
bastille config TARGET set enforce_statfs=1;
bastille config TARGET set allow.mount;
bastille config TARGET set allow.mount.fdescfs;
bastille restart TARGET
```

TEMPLATE:
```
CONFIG set enforce_statfs=1;
CONFIG set allow.mount;
CONFIG set allow.mount.fdescfs;
RESTART
```

Likely need to restart the container after making these changes.

**Comment by scruffydan** [comment]
Thank you. the template options worked and did exactly what I was looking for!
