### ISSUE TITLE
[DOCUMENTATION] Update documentation on release upgrade

### ISSUE THREAD

**Issue by Ludenson** [BastilleBSD/bastille#557]
[Edit]
After some searching I found the document [Jail Upgrades](https://gist.github.com/cedwards/1e00c3d0aa6fbb14bc5b16fca8df0c35) through [Reddit](https://www.reddit.com/r/freebsd/comments/msz1v8/bastillebsd_upgrade_jails_to_130release/).
This document should be merged with [Examples: Releases](https://bastille.readthedocs.io/en/latest/chapters/targeting.html) in the documentation (including your [comment](https://gist.github.com/cedwards/1e00c3d0aa6fbb14bc5b16fca8df0c35?permalink_comment_id=4302882#gistcomment-4302882) at the bottom) - or at least referenced.

[Question]
Does `bootstrap` take arguments - as in `bastille bootstrap 13.1-RELEASE update` - or is it just two commands in series..?
This might also be an update to the documentation... :-)

This is not a bug, but lack of clear documentation of the release upgrade process for average users like me :-)

**Describe the bug**
Doing a 
`bastille upgrade 13.0-RELEASE 13.1-RELEASE` 
and then
`bastille update 13.0-RELEASE` 
reverts the 13.0-RELEASE-jail from the newly updated FreeBSD version 13.1-RELEASE-p3 to a "dirty" FreeBSD version 13.0-RELEASE-p13

[Edit:]
Using the -f flag does not solve the problem or change the described behavior.
`bastille upgrade 13.0-RELEASE 13.1-RELEASE -f`

Running as root instead of using sudo doesn't change described behavior (didn't think so).

**Bastille and FreeBSD version**
> \> sudo bastille -v && freebsd-version -kru
 0.9.20220714
 13.1-RELEASE-p3
 13.1-RELEASE-p3
 13.1-RELEASE-p3

**How did you install bastille? (port/pkg/git)**
pkg

**Steps to reproduce?**
> \> sudo **bastille upgrade 13.0-RELEASE 13.1-RELEASE**
 src component not installed, skipped
 Looking up update.FreeBSD.org mirrors... 2 mirrors found.
 Fetching metadata signature for 13.0-RELEASE from update1.freebsd.org... done.
 Fetching metadata index... done.
 Fetching 1 metadata patches. done.
 Applying metadata patches... done.
 Fetching 1 metadata files... done.
 Inspecting system... done.
> 
> The following components of FreeBSD seem to be installed:
 kernel/generic world/base
> 
> The following components of FreeBSD do not seem to be installed:
 kernel/generic-dbg world/base-dbg world/lib32 world/lib32-dbg
> 
> Does this look reasonable (y/n)? **y**
> 
> Fetching metadata signature for 13.1-RELEASE from update1.freebsd.org... done.
 Fetching metadata index... done.
 Fetching 1 metadata patches. done.
 Applying metadata patches... done.
 Fetching 1 metadata files... done.
 Inspecting system... done.
 Fetching files from 13.0-RELEASE for merging... done.
 Preparing to download files... done.
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
 /usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
/usr/sbin/freebsd-update: cannot open files/.gz: No such file or directory
> Attempting to automatically merge changes in files... done.
> 
> The following file will be removed, as it no longer exists in
 FreeBSD 13.1-RELEASE: /etc/defaults/devfs.rules
 Does this look reasonable (y/n)? **n**
> 
> Please run 'bastille upgrade 13.0-RELEASE install' to finish installing updates.
 \> sudo **bastille upgrade 13.0-RELEASE install**
 src component not installed, skipped
 No updates are available to install.
 Run '/usr/sbin/freebsd-update fetch' first.
> \> sudo **bastille console test**   (using the 13.0-RELEASE-jail)
[test]:
root@test:~ # **uname -aKU**
FreeBSD test 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64 1301000 1301000
root@test:~ # **cat /etc/os-release**
NAME=FreeBSD
VERSION=13.0-RELEASE-p13
VERSION_ID=13.0
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 13.0-RELEASE-p13"
CPE_NAME=cpe:/o:freebsd:freebsd:13.0
HOME_URL=https://FreeBSD.org/
BUG_REPORT_URL=https://bugs.FreeBSD.org/
root@test:~ # **exit**
> \> sudo **bastille cmd test freebsd-version**
[test]:
13.0-RELEASE-p13
[test]: 0
> 
> \> sudo **bastille update 13.0-RELEASE**
src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for **13.0-RELEASE** from update2.freebsd.org... done.
Fetching metadata index... done.
Fetching 1 metadata patches. done.
Applying metadata patches... done.
Fetching 1 metadata files... done.
Inspecting system... done.
Preparing to download files... done.
The following files will be added as part of updating to
**13.0-RELEASE-p13**:           (noooo, WRONG version!)
/usr/include/c++/v1/tr1/barrier
/usr/include/c++/v1/tr1/concepts
/usr/include/c++/v1/tr1/execution
/usr/include/c++/v1/tr1/latch
/usr/include/c++/v1/tr1/numbers
/usr/include/c++/v1/tr1/semaphore
> 
> WARNING: FreeBSD 13.0-RELEASE HAS PASSED ITS END-OF-LIFE DATE.
Any security issues discovered after Wed Aug 31 02:00:00 CEST 2022
will not have been corrected.
\> sudo **bastille cmd test freebsd-version**
[test]:
13.0-RELEASE-p13
[test]: 0
> 
> \>

<s>Now I have to do the `bastille upgrade` again and never use `bastille update`...</s>

**Expected behavior**
The scenario I was expecting:
> \> sudo **bastille update 13.0-RELEASE**
src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for **13.1-RELEASE** from update1.freebsd.org... done.
Fetching metadata index... done.
Fetching 2 metadata patches.. done.
Applying metadata patches... done.
Fetching 2 metadata files... done.
Inspecting system... done.
Preparing to download files... done.
> 
> No updates needed to update system to **13.1-RELEASE-p3**.

(like on the host-system)

**Comment by bmac2** [comment]
Documentation was just updated in this manner in the release a couple of  days ago.  Marking as closed.
