### ISSUE TITLE
Gitlab template is broken

### ISSUE THREAD

**Issue by Efiartes** [BastilleBSD/bastille#565]
**[MANDATORY] Describe the bug [MANDATORY]**
GitLab template generates connection errors to 127.0.0.1 ip address, and finally installer brokes down.
Error messages are like that:
`.{"timestamp":"2022-12-30T10:00:26.124Z","pid":6572,"message":"! Unable to load application: ActiveRecord::ConnectionNotEstablished: could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432?\n"}`

`
/usr/local/lib/ruby/gems/3.0/gems/pg-1.3.5/lib/pg/connection.rb:702:in connect_start: could not connect to server: Connection refused (PG::ConnectionBad)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
`

As consecuence of the error, Gitlab is not started:
```
bastille cmd BaudBeauty sockstat -46 -l -s
[BaudBeauty]:
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS       PATH STATE   CONN STATE  
[BaudBeauty]: 0
```

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.9.20220714
13.1-RELEASE-p5
13.1-RELEASE-p5
13.1-RELEASE-p5

**[MANDATORY] How did you install bastille? (port/pkg/git)**
From pakacges:
```
pkg info bastille
bastille-0.9.20220714
Name           : bastille
Version        : 0.9.20220714
Installed on   : Fri Dec 30 07:51:17 2022 CET
Origin         : sysutils/bastille
Architecture   : FreeBSD:13:*
Prefix         : /usr/local
Categories     : sysutils
Licenses       : BSD3CLAUSE
Maintainer     : christer.edwards@gmail.com
WWW            : https://bastillebsd.org
Comment        : Jail automation framework
Annotations    :
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 250KiB
Description    :
Bastille helps you quickly create and manage FreeBSD Jails.

The project focuses on secure defaults, automation and
repeatable templates.

WWW: https://bastillebsd.org
```

**[optional] Steps to reproduce?**
bastille bootstrap https://gitlab.com/bastillebsd-templates/gitlab-ce
bastille create -T BaudBeauty 13.1-RELEASE 192.168.69.16 nfe0
bastille template BaudBeauty bastillebsd-templates/gitlab-ce

**[optional] Expected behavior**
A clean installation process without errors
[error_log.txt](https://github.com/BastilleBSD/bastille/files/10324149/error_log.txt)
 and Gitlab service working.

**[optional] Screenshots**

**[optional]  Additional context**
I have attached an error_log.txt file where you can see all the template process to the last error.

**Comment by yaazkal** [comment]
Hi, labeling this as `wontfix` since it's a topic related to the template and the behavior for the app installed by it but not to Bastille or its commands.

I guess this is the repo of the template you are talking about: https://gitlab.com/bastillebsd-templates/gitlab-ce

So feel free to open an issue there.
