### ISSUE TITLE
QUESTION: how to delete bootstrapped release/template?

### ISSUE THREAD

**Issue by jhfoo** [BastilleBSD/bastille#570]
Tried to `rm -rf /usr/local/bastille/releases` and some folders cannot be deleted. These are releases not used in any jail but they seem to be locked ('Operation not permitted' and 'Directory not empty').

Notice releases are also mapped to cache/ as well.

Any advice?

**Comment by cedwards** [comment]
Try `chflags noschg /usr/local/bastille/releases` to remove those restrictions.

**Comment by jhfoo** [comment]
Thanks. Tried but no change. Is it possible it's caused by the fact that I use ZFS?

If I do `zfs list` I get
```
zroot/bastille/cache/12.3-RELEASE           192K  31.2G      192K  /usr/local/bastille/cache/12.3-RELEASE
...
zroot/bastille/releases                     559M  31.2G      192K  /usr/local/bastille/releases
zroot/bastille/releases/12.3-RELEASE       2.74M  31.2G     2.74M  /usr/local/bastille/releases/12.3-RELEASE
```

**Comment by scruffydan** [comment]
Those are ifs data sets not regular directories. Try `zfs destroy -r /usr/local/bastille/cache/12.3-RELEASE`

**Comment by jhfoo** [comment]
I tried the above and got the following response:
```
%sudo zfs destroy -r /usr/local/bastille/cache/12.3-RELEASE                                                  
cannot open '/usr/local/bastille/cache/12.3-RELEASE': leading slash in name
```

**Comment by scruffydan** [comment]
Yep that was my mistake,  It might work if you just remove the leading slash but this should also work: `zfs destroy -r zroot/bastille/releases/12.3-RELEASE`

**Comment by jhfoo** [comment]
Ok here's some successful updates:

`zfs destroy -r zroot/bastille/cache/12.3-RELEASE` works.

Additional cleanup steps:
1. `rm -rf /usr/local/bastille/cache/12.3-RELEASE`
2. Do the same for releases/12.3-RELEASE
