### ISSUE TITLE
[BUG] "ALL" not properly enumerating all jails completely in cmd script

### ISSUE THREAD

**Issue by nuintari** [BastilleBSD/bastille#589]
ALL is getting passed literally into the check for linsysfs on line 56 of "/usr/local/share/bastille/cmd.sh" instead of being enumerated as each active jail:

----------------------------

root@pub-dns-j1:~ # bastille cmd ALL freebsd-version
[pub-dns-a1]:
grep: /opt/bastille/jails/ALL/fstab: No such file or directory
13.2-RELEASE
[pub-dns-a1]: 0

[pub-dns-r1]:
grep: /opt/bastille/jails/ALL/fstab: No such file or directory
13.2-RELEASE
[pub-dns-r1]: 0

----------------------------

I think it just needs a modification to include something similar to this:

if [ "${TARGET}" = 'ALL' ]; then
    JAILS=$(bastille list jails)
fi

Around line 51 of "/usr/local/share/bastille/cmd.sh"

**Comment by JRGTH** [comment]
What `bastille` version you are running?

I can't reproduce it:

```
root@nas-mserver: ~# bastille -v
0.9.20220714
root@nas-mserver: ~# bastille cmd ALL freebsd-version
[plex]:
13.1-RELEASE-p7
[plex]: 0

[jail1]:
13.1-RELEASE-p7
[jail1]: 0

[jail2]:
13.1-RELEASE-p7
[jail2]: 0
```
Seems this has been fixed already.

**Comment by nuintari** [comment]
root@pub-dns-j1:/usr/local/share/bastille # bastille -v
0.9.20220714

I'm not running any Linux jails, so it doesn't break anything for me, just thought I'd found an issue

**Comment by yaazkal** [comment]
Can't reproduce it either, I'm using HEAD:

```
yaazkal@noc:~ $ sudo bastille cmd ALL freebsd-version
[adguard]:
13.2-RELEASE
[adguard]: 0

[prometheus]:
13.2-RELEASE
[prometheus]: 0

[dashboard]:
13.2-RELEASE
[dashboard]: 0

```
