### ISSUE TITLE
[BUG] Start of VNET Jails only possible once 'bastille create -V' has been invoked

### ISSUE THREAD

**Issue by joh-ku** [BastilleBSD/bastille#597]
**[MANDATORY] Describe the bug [MANDATORY]**
I want to migrate some Bastille Jails from Host A to Host B.
On host A I've exported the Jails with `bastille export --gz <JAIL>`.
On host B I've installed Bastille from ports and bootstrapped `13.2-RELEASE`. 
Then I've imported the first Jail.
The import succeeded, but when starting the Jail, I get the following error message:

```
jail: myjail: exec jib: No such file or directory
jail: myjail: jib addm bastille0 vmx0: failed
```
The problem is, that the [jib](https://cgit.freebsd.org/src/tree/share/examples/jails/jib?h=stable/13) script is only copied over to `/usr/local/bin/jib` when "[bastille create](https://github.com/BastilleBSD/bastille/blob/61e7084b335fa6fcdfa70988da57d5c365f431bc/usr/local/share/bastille/create.sh#L469-L477)" is invoked on a VNET enabled jail.
As this was not the case in my scenario, `jib` was missing after the Jail has been imported.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.9.20220714
13.2-RELEASE
13.2-RELEASE
13.2-RELEASE

**[MANDATORY] How did you install bastille? (port/pkg/git)**
Installed from ports.

**[optional] Expected behavior**
To avoid this, the availability of `jib` could be checked in [start.sh](https://github.com/BastilleBSD/bastille/blob/61e7084b335fa6fcdfa70988da57d5c365f431bc/usr/local/share/bastille/start.sh) instead.

**Comment by bmac2** [comment]
fixed by @JRGTH in and merged to main.
