### ISSUE TITLE
[BUG] update release fails to apply EOL security patch

### ISSUE THREAD

**Issue by tucoinfo** [BastilleBSD/bastille#601]
**[MANDATORY] Describe the bug [MANDATORY]**
`bastille update 13.1-RELEASE` fails to apply update from p6 to p9

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
```
# bastille -v && freebsd-version -kru
0.9.20220714
13.2-RELEASE-p2
13.2-RELEASE-p2
13.2-RELEASE-p2
```
Previously 13.1-RELEASE-p9, same issue.

**[MANDATORY] How did you install bastille? (port/pkg/git)**
Ports

Really enjoying BastilleBSD, thank you. I realise I could try to delete the release and bootstrap+update again or just upgrade but I'm curious.

Is it possible that the EOL status of 13.1 causes the issue?

```
# bastille list release -p
11.2-RELEASE
12.3-RELEASE-p9
13.1-RELEASE-p6
```
```
# bastille list all
 JID      State  IP Address  Published Ports  Hostname  Release          Path
 mariadb  Up     10.0.0.40   -                mariadb   13.1-RELEASE-p6  /usr/local/bastille/jails/mariadb/root
 netdata  Up     10.0.0.20   -                netdata   13.1-RELEASE-p6  /usr/local/bastille/jails/netdata/root
 php8     Up     10.0.0.30   -                php8      13.1-RELEASE-p6  /usr/local/bastille/jails/php8/root
 rel112   Up     10.0.0.11   -                rel112    11.2-RELEASE     /usr/local/bastille/jails/rel112/root
 rel123   Up     10.0.0.10   -                rel123    12.3-RELEASE-p9  /usr/local/bastille/jails/rel123/root
```
```
# bastille cmd mariadb freebsd-version -u
[mariadb]:
13.1-RELEASE-p6
[mariadb]: 0
```
```
# bastille update 13.1-RELEASE
src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for 13.1-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.
The following files will be updated as part of updating to
13.1-RELEASE-p9:
/bin/freebsd-version
/boot/loader
...
/var/db/etcupdate/current/etc/ssh/sshd_config
/var/db/mergemaster.mtree

WARNING: FreeBSD 13.1-RELEASE HAS PASSED ITS END-OF-LIFE DATE.
Any security issues discovered after Mon Jul 31 02:00:00 CEST 2023
will not have been corrected.
```
```
# bastille list release -p
11.2-RELEASE
12.3-RELEASE-p9
13.1-RELEASE-p6
# bastille cmd mariadb freebsd-version -u
[mariadb]:
13.1-RELEASE-p6
[mariadb]: 0
```
Restarted host and jails, `bastille verify` shows no errors.

**Comment by yaazkal** [comment]
I see you just get a warning, not an error, but from the `freebsd-update` command, not by Bastille. Also check in the future if you have restarted the jail so the version is correctly reflected.

I recommend to keep your jails with more recent versions of FreeBSD and avoid using EOL versions since they get deleted from the downloads folder (Bastille hast no control of that), that affects bootstrapping them. You can also try to use a recent version of Bastille like `0.10.20230714` that was recently released.

**Comment by tucoinfo** [comment]
Thanks for answering @yaazkal. Yes as mentioned I restarted host+jails.

13.1-RELEASE-p9 is only 2 weeks old and still in `/var/db/freebsd-update/` as are much older updates. As mentioned I first noticed the issue before updating the host to 13.2, when it was still on 13.1-RELEASE-p9.

I don't recall seeing `freebsd-update` clear out the cache and especially not a previous release that a rollback would require - which is the case here. I have always deleted the cache manually when I need to reclaim space.

The `0.10.x` update is not yet in [ports](https://www.freshports.org/sysutils/bastille/) and I'm not sure I see this issue in the [commit log](https://github.com/BastilleBSD/bastille/releases/tag/0.10.20230714).

I just tried `rm -rf /var/db/freebsd-update/*` in case of some corruption. The update downloads again OK but is still not applied to the base release.

I'll keep searching and report back.

**Comment by tucoinfo** [comment]
OK so I made some progress.

The `release_update()` script hasn't been updated since the current ports version `0.9.20220714` so it's not worth upgrading for this issue.

If I echo the command it looks OK according to [freebsd-update(8)](https://man.freebsd.org/cgi/man.cgi?freebsd-update(8)).

`freebsd-update --not-running-from-cron -b "/usr/local/bastille/releases/13.1-RELEASE" fetch install --currently-running "13.1-RELEASE"`

But running that command directly still does not *apply* the update. Running again with just `install` works.

```
root@bastille:~ # freebsd-update --not-running-from-cron -b "/usr/local/bastille/releases/13.1-RELEASE" install --currently-running "13.1-RELEASE"
src component not installed, skipped
Installing updates...
Restarting sshd after upgrade
Performing sanity check on sshd configuration.
Stopping sshd.
Waiting for PIDS: 2099.
Performing sanity check on sshd configuration.
Starting sshd.
Scanning /usr/local/bastille/releases/13.1-RELEASE/usr/share/certs/blacklisted for certificates...
Scanning /usr/local/bastille/releases/13.1-RELEASE/usr/share/certs/trusted for certificates...
 done.
root@bastille:~ # bastille list release -p
11.2-RELEASE
12.3-RELEASE-p9
13.1-RELEASE-p9
```
By deduction I can assume that there is a `fetch` return code that exits before `install`.

So my initial assumption seems correct. EOL does indeed break `bastille update`.

Et voilà : [Bug 258918](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258918)

A solution would be do split the update command.

Why bother? The _always upgrade releases_ mantra is fine in an ideal world. Jails are very useful for testing upgrade paths of outdated apps and systems. Not just for virtualisation.

**Comment by tucoinfo** [comment]
@bmac2 Sure, the analysis of the issue is "completed".

But without a fix all that time was wasted. Maybe you are doing that now, or should I submit a pull request?

**Comment by bmac2** [comment]
PR #613  fixes this issue.  Closing.  PR is in review and will be merged.
