### ISSUE TITLE
[BUG] can't create mountpoints for linux compat

### ISSUE THREAD

**Issue by socphoenix** [BastilleBSD/bastille#602]
**[MANDATORY] Describe the bug [MANDATORY]**
"bastille mount devfs      /compat/linux/dev      devfs      rw,late 0 0"  returns an error. There are several mount points needed to set up linux compat (useful for things like the onlyoffice built in to nextcloud). This worked in iocage but struggling to do that same here. The following mountpoints are needed:
`devfs      /compat/linux/dev      devfs      rw,late                    0  0

tmpfs      /compat/linux/dev/shm  tmpfs      rw,late,size=1g,mode=1777  0  0

fdescfs    /compat/linux/dev/fd   fdescfs    rw,late,linrdlnk           0  0

linprocfs  /compat/linux/proc     linprocfs  rw,late                    0  0

linsysfs   /compat/linux/sys      linsysfs   rw,late                    0  0`

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.9.20220714
13.2-RELEASE-p2

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg
**[optional] Steps to reproduce?**
"bastille mount devfs      /compat/linux/dev      devfs      rw,late 0 0"   on already existing jail.
**[optional] Expected behavior**
Expected it to add this to jails fstab correctly.

**Comment by michael-o** [comment]
Let me guess, you have that from the FreeBSD handbook. The information is incomplete in a sense that the mount happens from the host into the jail and not in the jail itself. This works for me based on [this](https://github.com/msimerson/Mail-Toaster-6/wiki/Linux-Jails):
```
root@deblndw013x:/usr/local/bastille/jails/deblndw013x1j
# cat fstab
devfs      /usr/local/bastille/jails/deblndw013x1j/root/compat/linux/dev      devfs      rw                    0  0
tmpfs      /usr/local/bastille/jails/deblndw013x1j/root/compat/linux/dev/shm  tmpfs      rw,size=1g,mode=1777  0  0
fdescfs    /usr/local/bastille/jails/deblndw013x1j/root/compat/linux/dev/fd   fdescfs    rw,linrdlnk           0  0
linprocfs  /usr/local/bastille/jails/deblndw013x1j/root/compat/linux/proc     linprocfs  rw                    0  0
linsysfs   /usr/local/bastille/jails/deblndw013x1j/root/compat/linux/sys      linsysfs   rw                    0  0
```
then in the jail I have:
```
root@deblndw013x1j:~
# mount
hp-large/bastille/jails/deblndw013x1j/root on / (zfs, local, noatime, nfsv4acls)
devfs on /compat/linux/dev (devfs, local, multilabel)
tmpfs on /compat/linux/dev/shm (tmpfs, local)
fdescfs on /compat/linux/dev/fd (fdescfs)
linprocfs on /compat/linux/proc (linprocfs, local)
linsysfs on /compat/linux/sys (linsysfs, local)
/usr/local/bastille/jails/deblndw013x1j.bak/root on /old (nullfs, local)
devfs on /dev (devfs, local, multilabel)
fdescfs on /dev/fd (fdescfs)
procfs on /proc (procfs, local)
```
I guess this is what you are looking for!

Then:
```
root@deblndw013x1j:/home/ldacafe/testing/mtbf-tool
# file bin/FT_Eval
bin/FT_Eval: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.0.0, BuildID[sha1]=8dfb5116a73e3ae07561e885678bbff9ed63084a, with debug_info, not stripped
root@deblndw013x1j:/home/ldacafe/testing/mtbf-tool
# ll /compat/linux/lib64/ld-linux-x86-64.so.2
lrwxr-xr-x  1 root  wheel  10 2022-05-18 17:57 /compat/linux/lib64/ld-linux-x86-64.so.2@ -> ld-2.17.so
root@deblndw013x1j:/home/ldacafe/testing/mtbf-tool
# bin/FT_Eval
RAM Kernel (R_4.4) Error Message

Error when executing bin/FT_Eval:
  ERROR: Could not open file 'FT_Spec.txt' with mode 'r' for reading
```

Note that additional `allow.mounts` are important!

**Comment by bmac2** [comment]
@socphoenix is the solution given by @michael-o sufficient?  I am assuming it worked for you.  Marking closed as answered.
