### ISSUE TITLE
[BUG] Add git as a dependency

### ISSUE THREAD

**Issue by jakefrancois** [BastilleBSD/bastille#603]
**[MANDATORY] Describe the bug [MANDATORY]**
bastille bootstrap "TEMPLATE_REPO" 
The command above requires git to function, which is not part of the FreeBSD base

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
[0.9.20220714] 13.2-RELEASE
**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg
**[optional] Steps to reproduce?**
fresh install of FreeBSD, pkg install bastille, bastille bootstrap "TEMPLATE_REPO" 
**[optional] Expected behavior**
git is installed as a dependency

**[optional] Screenshots**

**[optional]  Additional context**

**Comment by michael-o** [comment]
I think how the user manages the templates it is up to him. I use Subversion, for example because it simply works and there is not counterpart for `svn:externals`.

**Comment by bmac2** [comment]
Added a section detailing that git is a requirement for template usage on the new template repo.
