### ISSUE TITLE
[DOCUMENTATION] Getting started documentation incorrect

### ISSUE THREAD

**Issue by mcse3010** [BastilleBSD/bastille#607]
In the getting started docs:
[https://bastillebsd.org/getting-started/](https://bastillebsd.org/getting-started/)

It tells you an example command to create the container is the following:
`bastille create alcatraz 13.1-RELEASE 10.17.89.50`

But doing so yields a container with no networking enabled.  The interface should be specified as in the example:
`bastille create alcatraz 13.1-RELEASE 10.17.89.50 vtnet0`

This is specified in the networking documentation but not in the getting started, leading to some frustration.

**Comment by adriel-tech** [comment]
If Bastille is setup correctly "bastille create alcatraz 13.1-RELEASE 10.17.89.50" will create a jail using bastille0 Interface with ip 10.17.89.50 with working internet. Unless you have some weirdness in your /etc/resolve.conf messing with the jails dns.

**Comment by michael-o** [comment]
> If Bastille is setup correctly which requires pf to be enabled and relevant content in /etc/pf.conf. "bastille create alcatraz 13.1-RELEASE 10.17.89.50" will create a jail using bastille0 Interface, ip 10.17.89.50 with working internet. Unless you have some weirdness in your /etc/resolve.conf messing with the jails dns.

That is not correct. Bastille does not require pf at all. I run VNET only jails it works w/o touching pf on the host at all.

**Comment by adriel-tech** [comment]
Sure but the starter/install guides goes through the steps to setup pf and assumes you have done so.

**Comment by michael-o** [comment]
Related to #346.

**Comment by bmac2** [comment]
install guides if followed works as advertised for non-vnet jails.
