### ISSUE TITLE
[QUESTION] Is bastille orchestratable/clusterable?

### ISSUE THREAD

**Issue by OneOfTheJohns** [BastilleBSD/bastille#609]
Hi, i was not able to find any information about orchestration topic for bastille anywhere, and so here am with maybe dumb question. But im really interested in finding something to manage multiple Freebsd instances, with multiple jails in each of those instances in a cloud environment, and of course in a sane (in question of manageability and scalability) way. So is there any orchestration tool that can be used with bastille like Nomad or kubernetes? or maybe something is already built in? Thank you in advance.

**Comment by frenata** [comment]
I'm just another interested user, but I think I saw mentioned somewhere that folks have used Nomad / rawexec; my guess is you find that about as appetizing as I do. 

*However*, while I do see that there's a community supported driver for [pot](https://developer.hashicorp.com/nomad/plugins/drivers/community/pot) and a [driver authoring guide](https://developer.hashicorp.com/nomad/docs/concepts/plugins), so there is a plausible path to a "sane way".

**Comment by bmac2** [comment]
@cedwards do you want to address this question???

**Comment by bmac2** [comment]
@OneOfTheJohns @frenata  Per mine and Christer's conversations today this is on our list of possible roadmap items for the next release.  Currently we do not have orchestration (ala k8s)  set up, nor to my knowledge is there a tool out there native to jails that does this.   On the short list for future features.

**Comment by 2Belette** [comment]
I am also interested on cluster capability
