### ISSUE TITLE
[BUG] No networking and bastille hangs unlimited after upgrade

### ISSUE THREAD

**Issue by jan0sch** [BastilleBSD/bastille#625]
**[MANDATORY] Describe the bug [MANDATORY]**
After upgrading from 0.9.20220714 to 0.10.20231013 I experience the following two problems:

1. creating jails no longer works (bastille hangs, until ctrl+c is pressed)
2. no networking anymore in jails (i.e. no connection to the outside world)
3. stopping jails no longer works (bastille hangs)

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**

```txt
0.10.20231013
13.2-RELEASE-p4
13.2-RELEASE-p4
13.2-RELEASE-p4
```

**[MANDATORY] How did you install bastille? (port/pkg/git)**

pkg

**[optional] Steps to reproduce?**

- create a new jail
- try to stop an existing/running jail

**[optional] Expected behavior**

Bastille should work like before.

**[optional] Screenshots**

```
# bastille create test-with-current 13.2-RELEASE 192.168.0.10
grep: Warnung: überzähliges \ vor /
grep: Warnung: überzähliges \ vor /
Valid: (192.168.0.10).

Creating a thinjail...

pfctl: Invalid argument.
[test-with-current]:
test-with-current: created

[test-with-current]:
Applying template: default/thin...
[test-with-current]:
Applying template: default/base...
[test-with-current]:
[test-with-current]: 0

[test-with-current]:
syslogd_flags: -s -> -ss

[test-with-current]:
sendmail_enable: NO -> NO

[test-with-current]:
sendmail_submit_enable: YES -> NO

[test-with-current]:
sendmail_outbound_enable: YES -> NO

[test-with-current]:
sendmail_msp_queue_enable: YES -> NO

[test-with-current]:
cron_flags:  -> -J 60

[test-with-current]:
/etc/resolv.conf.bak -> /XXX/jails/test-with-current/root/etc/resolv.conf

Template applied: default/base

Template applied: default/thin
```

Then the prompt never returns. Stopping also never returns.

**[optional]  Additional context**

I'm running with a shared cloned local interface (`bastille0`) and the pf firewall. If I downgrade Bastille manually (via ports) to 0.9.20220714 then it runs fine just as before.

So far I have experienced the same behaviour on 7 machines (all using the "bastille0 approach" and pf) having the same versions of FreeBSD and Bastille.

The message `pfctl: Invalid argument.` seems to indicate a firewall problem, however it did not appear everytime but the outcome was. :-(

**Comment by cedwards** [comment]
This release made a few minor changes to the `bastille.conf`. Due to the way FreeBSD packages are handled, these changes are not automagically merged into an existing config.

My suggestion is to:
```
cd /usr/local/etc/bastille
vimdiff bastille.conf bastille.conf.sample
```

Merge the 2-3 lines from the sample that aren't present in the existing config and your problem should be resolved.

**Comment by jan0sch** [comment]
Thanks for the quick answer. That did solve my problem! :heart: 

One thing though: Can it be that the `destroy` command no longer works? I always get `Usage: bastille destroy [force] | [container|release]` and no jail is deleted.
