### ISSUE TITLE
[BUG] Upgrading jail from 13.2 -> 14.0 fails when trying to upgrade packages

### ISSUE THREAD

**Issue by tobybryans** [BastilleBSD/bastille#652]
**[MANDATORY] Describe the bug [MANDATORY]**
Hi @cedwards ,

I've tried the latest jail upgrade instructions for a 13.2 -> 14.0 upgrade, but when I try to do the pkg upgrade it fails:

```bash
doas bastille pkg web-bryans upgrade -f
Password:
[web-bryans]:
ld-elf.so.1: Shared object "libssl.so.111" not found, required by "pkg"
```

and attempting to get a console also fails (although somewhat more silently):

```bash
┌──(builder㉿buur06)-[~]
└─$ doas bastille console web-bryans
Password:
[web-bryans]:


┌──(builder㉿buur06)-[~]
└─$
```

The edit I do to the jail fstab is from:
`/usr/local/bastille/releases/13.2-RELEASE /usr/local/bastille/jails/web-bryans/root/.bastille nullfs ro 0 0`
to:
`/usr/local/bastille/releases/14.0-RELEASE /usr/local/bastille/jails/web-bryans/root/.bastille nullfs ro 0 0`

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.9.20220714
14.0-RELEASE-p3
14.0-RELEASE-p3
14.0-RELEASE-p4

**[MANDATORY] How did you install bastille? (port/pkg/git)**
pkg

**[optional] Steps to reproduce?**
Have a 13.2 jail, do the major release upgrade to 14.0 as described here: https://bastille.readthedocs.io/en/latest/chapters/upgrading.html

**[optional] Expected behavior**
A bastille jail running with 14.0.

**[optional]  Additional context**
This jail was relatively recently created from a standard 13.2-RELEASE template which has been upgraded to -p9 from the initial 13.2 release. The host has just been upgraded to 14.0-RELEASE-p4 from 13.2-RELEASE-p9.

**Comment by louwe** [comment]
libssl has been upgraded in FreeBSD 14.0-RELEASE. I think you need to botostrap it first. 

Try `bastille cmd eb-bryans pkg-static bootstrap -f`

**Comment by jamesoff** [comment]
Not sure I have it all figure out yet, but I had to comment out the two `opie` releated lines in `/etc/pam.d/system` in my jail, as the libraries for that seem to be gone, and there was output complaining about them in `messages`. The opie lines aren't present on another 14.0 host so that seems like the right action.

**Comment by jamesoff** [comment]
This entry from UPDATING is related: https://cgit.freebsd.org/src/tree/UPDATING#n270

**Comment by tobybryans** [comment]
Thank you @louwe, @jamesoff that fixes everything, and some good tips for my notes. Appreciated.
