### ISSUE TITLE
Export ZFS jail give a false error of "Options --gz, --raw, --safe, --verbose are valid for ZFS configured systems only"

### ISSUE THREAD

**Issue by Elektrokongen** [BastilleBSD/bastille#661]
I noticed an false error that prevents me from exporting my ZFS  jails. There is a missing ! in the if statement on line 215 in the file /usr/local/share/bastille/export.sh

HERE IS THE CURRENT IF STATEMENT

if checkyesno bastille_zfs_enable; then
    if [ -n "${GZIP_EXPORT}" -o -n "${RAW_EXPORT}" -o -n "${SAFE_EXPORT}" -o "${OPT_ZSEND}" = "-Rv" ]; then
        error_exit "Options --gz, --raw, --safe, --verbose are valid for ZFS configured systems only."
    fi
fi

HERE IS THE FIX I IMPLEMENTED TO GET IT WORKING

if ! checkyesno bastille_zfs_enable; then
    if [ -n "${GZIP_EXPORT}" -o -n "${RAW_EXPORT}" -o -n "${SAFE_EXPORT}" -o "${OPT_ZSEND}" = "-Rv" ]; then
        error_exit "Options --gz, --raw, --safe, --verbose are valid for ZFS configured systems only."
    fi
fi

**Comment by Elektrokongen** [comment]
I am not used to the process of contribute to open source code, so I guess this was my clumsy way of contributing :) I will check if I can do a merge request as well

**Comment by JRGTH** [comment]
> I have made an update to the current master, but I need a branch with write rigths in order to commit the update :) I cant seem to find any button on Git that allows me to create a branch..

I can confirm and validate this small bug as well, Christer will review the PR and merge wen time permits, thanks for the bug report and fix.

**Comment by Elektrokongen** [comment]
I see a fork option yes. I will try that next time, thx 👍

**Comment by mgstoyanov** [comment]
What's the status of this? I hit the same issue and the fix mentioned seems to work. I don't mind opening a PR for it if that will help speed things up...

**Comment by KiriakosGeorgiou** [comment]
> What's the status of this? I hit the same issue and the fix mentioned seems to work. I don't mind opening a PR for it if that will help speed things up...

I suppose the committers of this fine utility are busy with their jobs like the rest of us :) thanks for the fix to @Elektrokongen so we ZFS users can enjoy no downtime backups.
