### ISSUE TITLE
Some jails not starting on boot

### ISSUE THREAD

**Issue by dkaparis** [BastilleBSD/bastille#678]
Some of my jails do not automatically start after boot, but stay down. Manually starting them with `bastille start` works without issue. I have not set `bastille_list` or `bastille_rcorder` and none of my jails have `KEYWORD: nostart` or such in configuration.
Setting `bastille_list=ALL` or explicitly listing all jail names does not affect the issue - the same jails remain down after boot until manually started.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**

```
0.10.20231125
13.2-RELEASE-p8
13.2-RELEASE-p8
13.2-RELEASE-p9
```

All jails are 13.2-RELEASE-p9.

Bastille installed through pkg.

**Comment by yaazkal** [comment]
Thanks, this has been fixed now. Do you want to try again installing Bastille from git?

**Comment by dkaparis** [comment]
It turned out my jails were failing to start on boot because they were trying to mount filesystems that were not available yet. Re-arranging fstab's solved the issue for me. Probably this can be closed.

**Comment by yaazkal** [comment]
ok, thanks for the feedback
