### ISSUE TITLE
[BUG] list release -p not showing patchlevel

### ISSUE THREAD

**Issue by cristianyxen** [BastilleBSD/bastille#680]
**[MANDATORY] Describe the bug [MANDATORY]**
When using the -p option to bastille list release, the patchlevel is not shown as it would be expected. In list_release() ${2} is checked for being "-p" https://github.com/BastilleBSD/bastille/blob/3a4ebc63bb84b66d456713e608be86e4cba3b637/usr/local/share/bastille/list.sh#L166 which is not the case in the subroutine because ${2} of list.sh is never handed over at https://github.com/BastilleBSD/bastille/blob/3a4ebc63bb84b66d456713e608be86e4cba3b637/usr/local/share/bastille/list.sh#L212

Fix might be to use ${2} as argument to list_release() at https://github.com/BastilleBSD/bastille/blob/3a4ebc63bb84b66d456713e608be86e4cba3b637/usr/local/share/bastille/list.sh#L212 and use ${1} inside of list_release() at https://github.com/BastilleBSD/bastille/blob/3a4ebc63bb84b66d456713e608be86e4cba3b637/usr/local/share/bastille/list.sh#L166

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.10.20231125
13.2-RELEASE-p10
13.2-RELEASE-p4
13.2-RELEASE-p10

**[MANDATORY] How did you install bastille? (port/pkg/git)**
port/pkg

**Comment by tschettervictor** [comment]
Somehow the ${2} is never passed to the "list_release" function. Not sure why though...

**Comment by tschettervictor** [comment]
#764 should fix this.

**Comment by tschettervictor** [comment]
PR merged.
@bmac2
