### ISSUE TITLE
[BUG] impossible to have spaces in mountpoints paths

### ISSUE THREAD

**Issue by cyrilst** [BastilleBSD/bastille#682]
**Description**
It's impossible to have spaces in mountpoints paths.

**Versions**
0.10.20231125
13.2-RELEASE-p10
13.2-RELEASE-p10
13.2-RELEASE-p10

**Installation**
with pkg

**Steps to reproduce**
``bastille mount azkaban '/host/path with spaces' jail/path`` does not work. The error is ``Detected invalid host path or incorrect mount type in FSTAB.``

**Expected behavior**
The mountpoint should allow spaces. I tried manually editing fstab and using the ``\040`` character instead of a space, and it works.

If my understanding is right, this behavior is caused by the use of ``awk``. Using ``/host\\040with\\040spaces`` passes the awk test, but then fails the ``-f`` test…

**Comment by tschettervictor** [comment]
This should be fixed in #778
Can you test and report back?
@cyrilst

**Comment by bmac2** [comment]
fixed with #778
