### ISSUE TITLE
[BUG] "bastille boostrap" gives spurious and wrong warning about "bastille_zfs_enable"

### ISSUE THREAD

**Issue by michael-o** [BastilleBSD/bastille#688]
**Describe the bug**
Running on a UFS-only host. Bootstrapping a new release (13.3-RELEASE):
```
# bastille bootstrap 13.3-RELEASE
$bastille_zfs_enable is not set properly - see rc.conf(5).
Bootstrapping FreeBSD distfiles...
$bastille_zfs_enable is not set properly - see rc.conf(5).
$bastille_zfs_enable is not set properly - see rc.conf(5).
/usr/local/bastille/cache/13.3-RELEASE/MANIFES        1046  B 9627 kBps    00s
/usr/local/bastille/cache/13.3-RELEASE/base.tx         205 MB 2116 kBps 01m39s
Validated checksum for 13.3-RELEASE: base.txz
MANIFEST: d10531d663cee5efeb7d696ca84ce90adacd1fae14dd249628fb74da0c7c2820
DOWNLOAD: d10531d663cee5efeb7d696ca84ce90adacd1fae14dd249628fb74da0c7c2820
Extracting FreeBSD 13.3-RELEASE base.txz.

Bootstrap successful.
See 'bastille --help' for available commands.
```
It is not clear why `$bastille_zfs_enable is not set properly - see rc.conf(5).` is displayed at all, but even if it carries out several problems.

**Bastille and FreeBSD version**
0.10.20231125
13.3-STABLE
13.3-STABLE
13.3-STABLE

**How did you install bastille? (port/pkg/git)**
pkg

**Root Cause**
* `bastille_zfs_enable` is not part of `rc.conf`. It does not make sense to mention `rc.conf(5)`, more than that it is confusing because the manpage of it does know nothing about bastille. It needs to be removed. I would understand: "see /usr/local/....bastille.conf".
* The default value is empty: https://github.com/BastilleBSD/bastille/blob/3a4ebc63bb84b66d456713e608be86e4cba3b637/usr/local/etc/bastille/bastille.conf.sample#L42
* The check is `checkisyesno`: https://github.com/BastilleBSD/bastille/blob/3a4ebc63bb84b66d456713e608be86e4cba3b637/usr/local/share/bastille/common.sh#L121-L140
* It is a simple copy and paste error from `rc.subr`

**Fix**
* Fix the default value
* change see message

**Comment by Dieken** [comment]
Same issue with https://github.com/BastilleBSD/bastille/issues/718

**Comment by michael-o** [comment]
> Same issue with #718

Just tried, cannot confirm, still happens spite the commit:
```
# bastille bootstrap  14.0-RELEASE
$bastille_zfs_enable is not set properly - see rc.conf(5).
Bootstrapping FreeBSD distfiles...
$bastille_zfs_enable is not set properly - see rc.conf(5).
/usr/local/bastille/cache//MANIFEST                   1046  B 9293 kBps    00s
```
Less warnings, but still not fixed.
