### ISSUE TITLE
Permissions error on Debian /var/log/journal [BUG]

### ISSUE THREAD

**Issue by paul-hammant** [BastilleBSD/bastille#690]
I created a jailed Debian bullseye using bastille-create.

I console in and `apt update` then `apt upgrade` and I'm told:

```
# apt upgrade 
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
#E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
Setting up systemd (247.3-7+deb11u4) ...
Failed to re-open '/var/log/journal': Permission denied
dpkg: error processing package systemd (--configure):
 installed systemd package post-installation script subprocess returned error exit status 73
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Is there some chmod/own needed in bastille-create for debian bullseye and above?

**Comment by msoudny** [comment]
Hello Paul,
sorry for the delay. Can you please tell me how you start the jail and how do you connect to it?
As well, can you run "ls /usr/local/bastille/jail/debianjail/root/dev/pts" from host and then "ls /dev/pts" from within the jail?

**Comment by bmac2** [comment]
@paul-hammant  Somour put a question above on this.  Can you answer him please so we can figure out a solution??

**Comment by paul-hammant** [comment]
Sorry, I can't remember and don't have BSDs to experiment with presently.  Most likely I was using command line tools to do things because I am focused on scripted repeatability.
