### ISSUE TITLE
[ENHANCEMENT] Support conditional ARGS or CMD in the Bastillefile

### ISSUE THREAD

**Issue by tschettervictor** [BastilleBSD/bastille#717]
**Is your feature request related to a problem? Please describe.**
Docker has the ability to containerize applications, and at the same time be able to be torn down and rebuilt using mount points. Could we get the Bastillefile to support conditions?

That way, we'd be able to run a template overtop existing data, and have the mount points picked up.
One example is Nextcloud. If we run our Bastillefile overtop of our existing nextcloud data, it will probably be overwritten. The Bastillfile could be configured in such a way that it will not overwrite the data somehow.

Either with conditional arguements (ie do a template hook if a certain condition is met)
Or have an ARG REINSTALL="true"

**Comment by mxruben** [comment]
Unfortunately no. Seems like it would be tricky to design a feature like this without having to complicate the Bastillefile format/parser. I don't mind using the workaround above, was mostly just checking to see if this was implemented.

**Comment by tschettervictor** [comment]
@mxruben 

We now have a system in place that if an ARG is not populated, Bastille will skip it and any lines containing it. 

Do you mind testing?

#1447
