### ISSUE TITLE
[BUG] "bastille-setup" fails at config when installed from PKG

### ISSUE THREAD

**Issue by LightBusterX** [BastilleBSD/bastille#718]
When using "bastille-setup" as root, right after installing, it fails at config, because it's searching for itself in the wrong folder.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.10.20231125
14.1-RELEASE-p3
14.1-RELEASE-p3
14.1-RELEASE-p3

**[MANDATORY] How did you install bastille? (port/pkg/git)**
By using "sudo pkg install bastille"

**[optional] Steps to reproduce?**
Just typing "sudo bastille setup" right after "sudo pkg install bastille"

**[optional] Expected behavior**
I suppose to not fail trying to search for "/usr/local/bastille" when "which bastille" is returning "/usr/local/bin/bastille". Also it fails when configuring pf, not before.

**[optional] Screenshots**

**[optional]  Additional context**
This has been tried in a VM with FreeBSD 14.1-RELEASE inside a Ubuntu 22.04 host with KVM.

**Comment by Dieken** [comment]
Fixed in https://github.com/BastilleBSD/bastille/commit/19c8c021c4359a917683a74828427cfab5fa4047  but not released to FreeBSD ports tree.

**Comment by Dieken** [comment]
@yaazkal could you release a new version?

**Comment by yaazkal** [comment]
@LightBusterX until @cedwards is able to a new release, you can install Bastille using this repository as this has been already solved.
