### ISSUE TITLE
[ENHANCEMENT] Be able to export jails by a stream with rclone

### ISSUE THREAD

**Issue by maumont-scality** [BastilleBSD/bastille#724]
**Is your feature request related to a problem?**

Local backup aren't backup.

Currently it is possible to export tar.gz of snapshot into a SMB or NFS.

S3 (for example) is a nice and convenant solution for storing external data especially with the rise of "selft-hosted" solution like minio or garage.

Currently, if you want to push to something elsewhere  than local or NFS / CIFS, the only solution is to back up locally on the disk, THEN push with rclone.

Can be very long if you have dozen of jails. This is more efficient to push directly through rclone backend.

And rclone knows how to consume input with a pipe.

**Describe the solution you'd like**

An import/export option to export directly with rclone.

**Describe alternatives you've considered**

Did some very simple and quick test (just for backup) with a S3 home server : 

```
stop the jail
tar -czf - /usr/local/bastille/jails/myjail | rclone -P rcat garage-test:jails-backup/myjail-test.tar
start the jail
```
Please note that finally the rclone backend can be s3 or google-drive or whatever you want !
And it works archive is pushed and once restore it contents all the files !

Like this you don't have to backup locally and then do another loop to push to an external storage solution.

**Additional context**
Further test to be done, with something more elegant.

**Comment by maumont-scality** [comment]
Off course I'm talking about backup with file/tarball . 

I didn't test the zfs snapshot but considering rclone can consume a pipe as input it should works as well.

**Comment by yaazkal** [comment]
Thank you for the message and the description. I don't see why this should be in Bastille core rather than a personal preference. I'll label it as "out of scope" and if no new activity or comments from the community comes it will be an indicative to close it.

Regards.

**Comment by bmac2** [comment]
I concur with @yaazkal that this is OOS for bastille itself.  Closing as will not do.
