### ISSUE TITLE
Double zpool reference?

### ISSUE THREAD

**Issue by kbcb** [BastilleBSD/bastille#732]
https://github.com/BastilleBSD/bastille/blob/beccb6ff20d3e3986862ae642b0513552ad98e27/usr/local/share/bastille/bootstrap.sh#L71

In my version bastille.conf.sample says:

`bastille_zfs_prefix="${bastille_zfs_zpool}/bastille"                  ## default: "${bastille_zfs_zpool}/bastille"`

That implies that the following line from `bootstrap.sh` line (and all similar below that line):

`    if [ -d "/${bastille_zfs_zpool}/${bastille_zfs_prefix}" ]; then`

contain a superfluent (and fatal) reference to ${bastille_zfs_zpool}.

Am I right? Or have I somewhere messed up?

--
Love 
KBCB

**Comment by tschettervictor** [comment]
No, you are correct. See #713 

@yaazkal recently commented that he will try to find time to fix this.

**Comment by kbcb** [comment]
Yes, @yaazkal you are right. This issue is the same as #713. Please join issues. Thank you.
