### ISSUE TITLE
[BUG] create by zfs return mount_nullfs question

### ISSUE THREAD

**Issue by guoderu157** [BastilleBSD/bastille#734]
**[MANDATORY] Describe the bug [MANDATORY]**
when i use` bastille create alcatraz 14.1-RELEASE 10.17.89.10/24 ` to create` ,tell me fails , report :

```
mount_nullfs: /usr/local/bastille/jails/alcatraz/root/.bastille: Resource deadlock avoided
jail: alcatraz: /sbin/mount -t nullfs -o ro /usr/local/bastille/releases/14.1-RELEASE /usr/local/bastille/jails/alcatraz/root/.bastille: failed
```
zfs_enable is YES and zfs_pool is zroot

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
bastille version:0.10.20231125
freebsd version:14.1-RELEASE

**[MANDATORY] How did you install bastille? (port/pkg/git)**
use pkg install

**[optional] Steps to reproduce?**

**[optional] Expected behavior**

**[optional] Screenshots**

**[optional]  Additional context**

**Comment by tschettervictor** [comment]
Have you tried rebooting? I’ve run into this issue where directories I was trying to mount were in use or something. Rebooting solved it though.

**Comment by yaazkal** [comment]
@guoderu157 did you tried what @tschettervictor proposed in the previous comment?

**Comment by guoderu157** [comment]
Yes, I tried creating the jail after a reboot, but the problem persists.this is Screenshots when i create.
![image](https://github.com/user-attachments/assets/340cb563-7407-4d6a-bf26-c0007954e9ed)

**Comment by bmac2** [comment]
I had something similar one time .  I uninstalled bastille, deleted the entire bastille directory tree and reinstalled and it was working fine.  I thought at the time I screwed up the install somehow.  If you delete and reinstall from source is the issue still there?

**Comment by guoderu157** [comment]
> I had something similar one time . I uninstalled bastille, deleted the entire bastille directory tree and reinstalled and it was working fine. I thought at the time I screwed up the install somehow. If you delete and reinstall from source is the issue still there?

ok,i tried it

**Comment by guoderu157** [comment]
But after I uninstalled and reinstalled, the problem did not occur
