### ISSUE TITLE
What’s the status of BastilleBSD?

### ISSUE THREAD

**Issue by tschettervictor** [BastilleBSD/bastille#736]
This is a rather simple question. Does bastille need developers or reviewers?

There are open issues and PRs going all the way back to 2022, and most of them look like they aren’t being answered.

Just curious, I like bastille, and would definitely be interested if someone decides to fork it and keep it rolling!

**Comment by bmac2** [comment]
it is still active development.  Just been a few irl issues with some people that has slowed things down.  I will be trying to sort and clean up some of the issues this weekend as I can.

**Comment by bmac2** [comment]
closing   BCM

**Comment by bmac2** [comment]
visit discord channel for more support.  Active devs in channels there answering questions.

**Comment by bmac2** [comment]
please join the discord channels and feel free to jump in and pull tickets.
