### ISSUE TITLE
[BUG] bastille template fails with cp: ... Not a directory

### ISSUE THREAD

**Issue by TLINDEN** [BastilleBSD/bastille#743]
**[MANDATORY] Describe the bug [MANDATORY]**
I am trying to add my own skel files to a jail. This fails due to /usr/share being a symlink.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**

```default
bastille -v && freebsd-version -kru
0.10.20231125
14.1-RELEASE-p5
14.1-RELEASE-p5
14.1-RELEASE-p5
```

**[MANDATORY] How did you install bastille? (port/pkg/git)**

pkg.

**[optional] Steps to reproduce?**

create `/usr/local/bastille/templates/services/$jail/usr/share/skel` and fill it with `dot.$config` files. Then add `cp /usr /` to Bastillefile.

**[optional] Expected behavior**
The stuff under `usr` in the template dir shall just be copied.

**[optional] Screenshots**
Output of `bastille template pubnix services/pubnix`:
```default
test: -l: unexpected operator
cp: /usr/local/bastille/jails/pubnix/root/usr/share: Not a directory
Failed to execute command: cp  
```

If I look at the directory specified in the error:
```default
l /usr/local/bastille/jails/pubnix/root/usr/share 
lrwxr-xr-x  1 root wheel 20 Nov 24 12:26 /usr/local/bastille/jails/pubnix/root/usr/share@ -> /.bastille/usr/share
```

I also tried to use the skel directory directly. Same template dir setup and in Bastillefile:

`CP usr/share/skel /usr/share/skel`

But the error persists:

```default
test: -l: unexpected operator
cp: /usr/local/bastille/jails/pubnix/root//usr/share/skel: No such file or directory
Failed to execute command: cp
```

**[optional]  Additional context**
I am setting up the jail using an [ansible playbook](https://repo.daemon.de/scip/bsdnix/src/branch/master/roles/pubnix/tasks/main.yaml). From there I copy the files to the template dir and execute the above command. However, I'm getting the same behavior when I do the same thing manually.

**Comment by yaazkal** [comment]
I remember handling some previous issue with `cp` for the `0.11` release, can you plase try again installing Bastille HEAD and not from `pkg`?

Regards.

**Comment by TLINDEN** [comment]
Yes, you're right, it works with HEAD as expected.

Many thanks!

**Comment by yaazkal** [comment]
You are welcome, thanks for confirming it.
