### ISSUE TITLE
bootstrap and create have different release validations

### ISSUE THREAD

**Issue by ketralnis** [BastilleBSD/bastille#77]
I was able to `bastille bootstrap 12.1-RELEASE`, but on trying to then create a new jail with that release:

```
# bastille create mail 12.1-RELEASE 192.168.1.2 lo1
Unknown Release.
Usage: bastille create name release ip | interface.
```

This looks to be because bootstrapping and [creating](https://github.com/BastilleBSD/bastille/blob/29565b22c8fb450d7117ff9c60ec76bd34135cac/usr/local/share/bastille/create.sh#L322) validate the release name in separate code paths. But doesn't it make sense that if I was able to bootstrap the release in the first place that creating a jail from that release should always work?

I think the release name validation logic should be moved into only occurring on `bootstrap`, and `create` should never validate the name at all, just that the requested release is in fact present on disk

(Note: I'm aware that the specific issue of 12.1 not being `create`-able is addressed in https://github.com/BastilleBSD/bastille/commit/9bc8837f77a689a3cde26188637c187f766c14e0 but the overall issue stands)

**Comment by cedwards** [comment]
We made some improvements to this recently. Can you verify the version you have installed?

I agree that there can be some improvement made to centralize the filter/validation code. Thank you for the feedback.

**Comment by hackacad** [comment]
+1 on closing this issue
lookup for releases is already working
