### ISSUE TITLE
pf table entry missing

### ISSUE THREAD

**Issue by bsdlme** [BastilleBSD/bastille#80]
In the Getting Started guide there's a pf.conf which should be copied to _/etc/pf.conf_.
There are the lines
```
table <jails> persist
nat on $ext_if from <jails> to any -> ($ext_if)
```
which enable NATing from the jails table on the external interface.
This table is never populated, though. One needs to run
```
pfctl -t jails -T add $some_jail_ip
```
to have a jail access the external network.

Could this be added to "start.sh"? Or alternatively drop the table line and nat the whole jail subnet?

**Comment by cedwards** [comment]
My guess at first glance is you must be using the version in ports, which is a little bit old. I'm waiting on a commit in ports now to bring it to 0.5.20191128. This version will populate the PF table as expected.

In previous releases we recommended using a `nat on $ext_if from bastille0:network to any...`, and the version you have should function using that config.

My recommendation is update to 0.5.20191128 and you should be set.

**Comment by bsdlme** [comment]
You're right. I'm running bastille-0.4.20191025, will upgrade now and report back. :)

**Comment by bsdlme** [comment]
You were right. I updated the port (and committed your PR). Now it's working as expected. Thank you!
