### ISSUE TITLE
Bastille does not provide a man page

### ISSUE THREAD

**Issue by cedwards** [BastilleBSD/bastille#91]
Leaving this here for any takers (or for future @cedwards )...

Bastille needs a man page. The tool provides help output, but a proper man page would be a nice addition.

**Comment by hackacad** [comment]
Started initial work on a man page.
As soon as it gets to a RC-1 I will be adding all features and options. For now rough overview seams reasonable.

https://github.com/BastilleBSD/bastille/pull/96
