### ISSUE TITLE
unable to re-bootstrap after updating bootstrap_archives in config

### ISSUE THREAD

**Issue by cedwards** [BastilleBSD/bastille#98]
This issue / question was raised in IRC and noting here...

In 0.5.x a user is unable to add bootstrap archives and re-bootstrap. The system reports "already bootstrapped" and is done.

It would be nice to have functionality that would allow later adding other distfiles such as `lib32`, `ports`, `src`, etc.

**Comment by JRGTH** [comment]
Hi, support for re-bootstrap additional distfiles has been added in commit [e0d7222](https://github.com/BastilleBSD/bastille/pull/97/commits/e0d722203a3422c97bb73b50503cd06492be8901)

Regards

**Comment by cedwards** [comment]
Closing this issue as fixed.
